import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import i18n from '../i18n';

export interface AppraisalDtcItem {
  code: string;
  category: 'P' | 'C' | 'B' | 'U' | string;
  description: string;
  status: 'STORED' | 'PENDING' | 'HISTORIC' | string;
  freezeFrame?: Record<string, string>;
}

export interface MaintenanceRecordItem {
  serviceName: string;
  date: string;
  km: number;
}

export interface AppraisalReportData {
  vin: string;
  vehicleMake: string;
  vehicleModel: string;
  vehicleYear: number;
  mileageKm?: number;
  healthScore: number; // 0 to 100
  dtcList: AppraisalDtcItem[];
  telemetrySnapshot?: {
    engineVoltage?: number;
    coolantTemp?: number;
    rpm?: number;
    fuelTrim?: string;
    dpfLoad?: string;
  };
  aiSummary?: string;
  maintenanceLogs?: MaintenanceRecordItem[];
  generatedAt?: string;
}

export class EcuReportService {
  /**
   * Generates a localized 26-language HTML Appraisal / ECU Snapshot Report
   */
  public static generateHtmlReport(data: AppraisalReportData): string {
    const lang = i18n.language || 'en';
    const reportDate = data.generatedAt || new Date().toISOString().split('T')[0];
    const isPro = true; // Pro feature verified upstream

    // Localized Headers using i18n with 26-language fallbacks
    const tTitle = i18n.t('report.title', { defaultValue: 'MotoCortex — ECU & Vehicle Appraisal Report' });
    const tSubtitle = i18n.t('report.subtitle', { defaultValue: 'Comprehensive Second-Hand Diagnostic & Telemetry Inspection' });
    const tVehicleInfo = i18n.t('report.vehicleInfo', { defaultValue: 'Vehicle Identification & ECU Metadata' });
    const tHealthScore = i18n.t('report.healthScore', { defaultValue: 'Overall ECU Health Score' });
    const tDtcSection = i18n.t('report.dtcSection', { defaultValue: 'Diagnostic Trouble Codes (DTC Audit)' });
    const tTelemetrySection = i18n.t('report.telemetrySection', { defaultValue: 'Live Telemetry & Sensor Snapshot' });
    const tMaintenanceSection = i18n.t('report.maintenanceSection', { defaultValue: 'Akıllı Garaj Service & Maintenance History' });
    const tAiSection = i18n.t('report.aiSection', { defaultValue: 'AI Doctor Overall Condition Analysis' });
    const tDisclaimer = i18n.t('report.disclaimer', { defaultValue: 'Disclaimer: This report is generated by MotoCortex diagnostic software. Physical inspection by a certified technician is recommended prior to vehicle acquisition.' });

    // Health Score Badge Color
    let scoreColor = '#22c55e'; // Green
    if (data.healthScore < 50) scoreColor = '#ef4444'; // Red
    else if (data.healthScore < 80) scoreColor = '#f59e0b'; // Amber

    // Format DTC Rows
    const dtcRows = data.dtcList.length > 0
      ? data.dtcList.map(dtc => `
        <tr>
          <td><span class="badge ${dtc.category}">${dtc.code}</span></td>
          <td>${dtc.category}</td>
          <td>${dtc.description}</td>
          <td><strong>${dtc.status}</strong></td>
        </tr>
      `).join('')
      : `<tr><td colspan="4" class="no-faults">${i18n.t('report.noFaults', { defaultValue: 'No active or historical fault codes stored in ECU memory.' })}</td></tr>`;

    // Format Maintenance Rows
    const maintenanceRows = (data.maintenanceLogs && data.maintenanceLogs.length > 0)
      ? data.maintenanceLogs.map(m => `
        <tr>
          <td>${m.date}</td>
          <td>${m.serviceName}</td>
          <td>${m.km.toLocaleString()} km</td>
        </tr>
      `).join('')
      : `<tr><td colspan="3" class="no-data">${i18n.t('report.noMaintenance', { defaultValue: 'No recorded service entries in Akıllı Garaj.' })}</td></tr>`;

    return `
<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <title>${tTitle}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #1e293b; background: #f8fafc; margin: 0; padding: 24px; }
    .container { max-width: 800px; margin: 0 auto; background: #ffffff; padding: 32px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
    .header { border-bottom: 3px solid #0f172a; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: center; }
    .brand { font-size: 24px; font-weight: 800; color: #0f172a; letter-spacing: -0.5px; }
    .brand span { color: #2563eb; }
    .report-date { font-size: 14px; color: #64748b; }
    h1 { font-size: 20px; color: #0f172a; margin: 0 0 8px 0; }
    .subtitle { font-size: 14px; color: #64748b; margin-bottom: 24px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }
    .card { background: #f1f5f9; padding: 16px; border-radius: 8px; }
    .card h3 { margin: 0 0 8px 0; font-size: 12px; text-transform: uppercase; color: #64748b; letter-spacing: 0.5px; }
    .card p { margin: 0; font-size: 16px; font-weight: 600; color: #0f172a; }
    .health-score { text-align: center; background: #f8fafc; border: 2px solid ${scoreColor}; border-radius: 12px; padding: 20px; margin-bottom: 24px; }
    .health-score-val { font-size: 48px; font-weight: 900; color: ${scoreColor}; }
    .section-title { font-size: 16px; font-weight: 700; color: #0f172a; margin: 24px 0 12px 0; border-left: 4px solid #2563eb; padding-left: 8px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
    th { background: #f8fafc; font-weight: 600; color: #475569; }
    .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-family: monospace; font-weight: 700; font-size: 12px; background: #e2e8f0; color: #0f172a; }
    .badge.P { background: #fee2e2; color: #991b1b; }
    .badge.C { background: #fef3c7; color: #92400e; }
    .badge.B { background: #dbeafe; color: #1e40af; }
    .badge.U { background: #f3e8ff; color: #6b21a8; }
    .no-faults { text-align: center; color: #16a34a; font-weight: 600; padding: 16px; }
    .no-data { text-align: center; color: #94a3b8; padding: 16px; }
    .ai-box { background: #eff6ff; border-left: 4px solid #2563eb; padding: 16px; border-radius: 0 8px 8px 0; font-size: 14px; line-height: 1.6; color: #1e3a8a; margin-bottom: 24px; }
    .disclaimer { font-size: 11px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 16px; margin-top: 32px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="brand">MOTO<span>CORTEX</span></div>
      <div class="report-date">${reportDate} | Language: ${lang.toUpperCase()}</div>
    </div>

    <h1>${tTitle}</h1>
    <div class="subtitle">${tSubtitle}</div>

    <!-- Health Score Badge -->
    <div class="health-score">
      <div style="font-size:12px; text-transform:uppercase; color:#64748b; font-weight:700;">${tHealthScore}</div>
      <div class="health-score-val">${data.healthScore} / 100</div>
    </div>

    <!-- Vehicle Metadata -->
    <div class="section-title">${tVehicleInfo}</div>
    <div class="grid">
      <div class="card">
        <h3>VIN (Vehicle Identification No)</h3>
        <p style="font-family:monospace;">${data.vin || 'N/A'}</p>
      </div>
      <div class="card">
        <h3>Make / Model / Year</h3>
        <p>${data.vehicleYear || ''} ${data.vehicleMake || ''} ${data.vehicleModel || ''}</p>
      </div>
      <div class="card">
        <h3>Mileage</h3>
        <p>${data.mileageKm ? `${data.mileageKm.toLocaleString()} km` : 'N/A'}</p>
      </div>
      <div class="card">
        <h3>Inspection Status</h3>
        <p style="color:${scoreColor};">${data.healthScore >= 80 ? 'PASSED' : data.healthScore >= 50 ? 'ATTENTION REQUIRED' : 'CRITICAL FAULTS'}</p>
      </div>
    </div>

    <!-- DTC Section -->
    <div class="section-title">${tDtcSection}</div>
    <table>
      <thead>
        <tr>
          <th>Code</th>
          <th>System</th>
          <th>Description</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        ${dtcRows}
      </tbody>
    </table>

    <!-- Telemetry Snapshot -->
    <div class="section-title">${tTelemetrySection}</div>
    <div class="grid">
      <div class="card">
        <h3>Battery Voltage</h3>
        <p>${data.telemetrySnapshot?.engineVoltage ? `${data.telemetrySnapshot.engineVoltage.toFixed(1)} V` : 'N/A'}</p>
      </div>
      <div class="card">
        <h3>Coolant Temperature</h3>
        <p>${data.telemetrySnapshot?.coolantTemp ? `${data.telemetrySnapshot.coolantTemp} °C` : 'N/A'}</p>
      </div>
      <div class="card">
        <h3>Fuel Trim (STFT / LTFT)</h3>
        <p>${data.telemetrySnapshot?.fuelTrim || 'Normal (±2%)'}</p>
      </div>
      <div class="card">
        <h3>DPF Soot Load</h3>
        <p>${data.telemetrySnapshot?.dpfLoad || 'N/A'}</p>
      </div>
    </div>

    <!-- AI Doctor Summary -->
    ${data.aiSummary ? `
      <div class="section-title">${tAiSection}</div>
      <div class="ai-box">${data.aiSummary}</div>
    ` : ''}

    <!-- Maintenance Records -->
    <div class="section-title">${tMaintenanceSection}</div>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Service Item</th>
          <th>Kilometers</th>
        </tr>
      </thead>
      <tbody>
        ${maintenanceRows}
      </tbody>
    </table>

    <!-- Disclaimer Footer -->
    <div class="disclaimer">${tDisclaimer}</div>
  </div>
</body>
</html>
    `;
  }

  /**
   * Saves the HTML appraisal report file locally and launches native share sheet
   */
  public static async exportAppraisalReport(data: AppraisalReportData): Promise<string> {
    const htmlContent = this.generateHtmlReport(data);
    const vinSanitized = (data.vin || 'VEHICLE').replace(/[^a-zA-Z0-9]/g, '_');
    const fileName = `MotoCortex_Appraisal_${vinSanitized}_${Date.now()}.html`;
    const filePath = `${FileSystem.documentDirectory}${fileName}`;

    await FileSystem.writeAsStringAsync(filePath, htmlContent, {
      encoding: FileSystem.EncodingType.UTF8,
    });

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(filePath, {
        mimeType: 'text/html',
        dialogTitle: i18n.t('report.shareTitle', { defaultValue: 'Share MotoCortex Appraisal Report' }),
        UTI: 'public.html',
      });
    }

    return filePath;
  }
}

export default EcuReportService;
