/**
 * OemDatabaseProvider.ts
 * 
 * MotoCortex OEM Diagnostic Database Provider.
 * Versioned database registry containing 65+ OEM feature activation definitions
 * across US, European, and Far East Asian (China, Korea, Japan) automotive brand groups.
 * Includes Risk Classification (LOW, MEDIUM, HIGH) & SFD Security Status.
 */

export type FeatureCategory = 
    | 'LIGHTING'
    | 'SOUND_ALERTS'
    | 'DISPLAY_INSTRUMENT'
    | 'DRIVING_COMFORT'
    | 'SECURITY_SAFETY';

export type FeatureRiskLevel = 'LOW' | 'MEDIUM' | 'HIGH';

export interface OEMFeatureDefinition {
    id: string;
    nameKey: string;
    descKey: string;
    defaultName: string;
    defaultDesc: string;
    make: string;
    category: FeatureCategory;
    targetEcuHeader: string;
    didHex: string;
    byteIndex: number;
    bitIndex: number;
    requiresSecurityAccess: boolean;
    securityLevel?: number;
    requiresExtendedSession: boolean;
    safetyLevel: 'LEVEL_0_READ_ONLY' | 'LEVEL_1_CLEAR_DTC' | 'LEVEL_2_ADAPTATION';
    riskLevel: FeatureRiskLevel;
    sfdProtected?: boolean;
    streetLegalNoteKey?: string;
}

const EXTENDED_OEM_FEATURES: OEMFeatureDefinition[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // 1. VAG GROUP (Volkswagen, Audi, SEAT, Skoda, Cupra, Porsche)
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'vag_staging_needle_sweep',
        nameKey: 'features.items.vag_staging_needle_sweep.name',
        descKey: 'features.items.vag_staging_needle_sweep.desc',
        defaultName: 'Gauge Staging / Needle Sweep',
        defaultDesc: 'Sweeps instrument needles to maximum upon ignition start.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7C0',
        didHex: '0D04',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_acoustic_lock_confirmation',
        nameKey: 'features.items.vag_acoustic_lock_confirmation.name',
        descKey: 'features.items.vag_acoustic_lock_confirmation.desc',
        defaultName: 'Acoustic Lock Confirmation Chirp',
        defaultDesc: 'Emits a short horn confirmation chirp upon key fob locking.',
        make: 'Volkswagen',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '709',
        didHex: '0620',
        byteIndex: 1,
        bitIndex: 3,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_american_parking_lights',
        nameKey: 'features.items.vag_american_parking_lights.name',
        descKey: 'features.items.vag_american_parking_lights.desc',
        defaultName: 'US Style Parking Lights',
        defaultDesc: 'Illuminates front turn signals continuously at 20% dimming with parking lights.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '709',
        didHex: '280C',
        byteIndex: 0,
        bitIndex: 4,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW',
        streetLegalNoteKey: 'features.legalDisclaimerUsLights'
    },
    {
        id: 'vag_drl_menu_toggle',
        nameKey: 'features.items.vag_drl_menu_toggle.name',
        descKey: 'features.items.vag_drl_menu_toggle.desc',
        defaultName: 'Daytime Running Lights (DRL) Menu Toggle',
        defaultDesc: 'Enables DRL ON/OFF checkbox in infotainment vehicle settings menu.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '709',
        didHex: '0901',
        byteIndex: 2,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_tear_wiping',
        nameKey: 'features.items.vag_tear_wiping.name',
        descKey: 'features.items.vag_tear_wiping.desc',
        defaultName: 'Windshield Tear Wiping',
        defaultDesc: 'Executes an additional final wipe 5 seconds after windshield washer use.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '709',
        didHex: '0E02',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_emergency_brake_flashing',
        nameKey: 'features.items.vag_emergency_brake_flashing.name',
        descKey: 'features.items.vag_emergency_brake_flashing.desc',
        defaultName: 'Emergency Brake Hazard Flashing',
        defaultDesc: 'Rapidly flashes brake lights and hazards under heavy emergency braking.',
        make: 'Volkswagen',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '709',
        didHex: '1204',
        byteIndex: 1,
        bitIndex: 5,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_cornering_lights',
        nameKey: 'features.items.vag_cornering_lights.name',
        descKey: 'features.items.vag_cornering_lights.desc',
        defaultName: 'Cornering Fog Lights',
        defaultDesc: 'Illuminates cornering fog light on steering wheel rotation side.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '709',
        didHex: '1408',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_comfort_mirror_folding',
        nameKey: 'features.items.vag_comfort_mirror_folding.name',
        descKey: 'features.items.vag_comfort_mirror_folding.desc',
        defaultName: 'Key Fob Comfort Mirror Folding',
        defaultDesc: 'Automatically folds side mirrors when lock button is held on key fob.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '772',
        didHex: '0B10',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_lap_timer',
        nameKey: 'features.items.vag_lap_timer.name',
        descKey: 'features.items.vag_lap_timer.desc',
        defaultName: 'Instrument Cluster Lap Timer',
        defaultDesc: 'Unlocks track lap timer display tab in instrument cluster screen.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7C0',
        didHex: '0D08',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_refuel_quantity',
        nameKey: 'features.items.vag_refuel_quantity.name',
        descKey: 'features.items.vag_refuel_quantity.desc',
        defaultName: 'Refuel Quantity Display',
        defaultDesc: 'Displays exact volume in liters required for a full fuel refuel.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7C0',
        didHex: '0D0E',
        byteIndex: 0,
        bitIndex: 4,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_traffic_sign_recognition',
        nameKey: 'features.items.vag_traffic_sign_recognition.name',
        descKey: 'features.items.vag_traffic_sign_recognition.desc',
        defaultName: 'Traffic Sign Recognition (VZE)',
        defaultDesc: 'Displays camera-detected speed signs in instrument cluster and HUD.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7A5',
        didHex: '0E1B',
        byteIndex: 1,
        bitIndex: 2,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM',
        sfdProtected: true
    },
    {
        id: 'vag_ambient_color_palette_30',
        nameKey: 'features.items.vag_ambient_color_palette_30.name',
        descKey: 'features.items.vag_ambient_color_palette_30.desc',
        defaultName: '30-Color Ambient Lighting Palette',
        defaultDesc: 'Unlocks 30 RGB interior lighting color picker in MIB infotainment menu.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '709',
        didHex: '3008',
        byteIndex: 0,
        bitIndex: 6,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_seatbelt_warning_mute',
        nameKey: 'features.items.vag_seatbelt_warning_mute.name',
        descKey: 'features.items.vag_seatbelt_warning_mute.desc',
        defaultName: 'Seatbelt Chime Deactivation',
        defaultDesc: 'Disables unbuckled seatbelt acoustic chime in instrument cluster.',
        make: 'Volkswagen',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '7C0',
        didHex: '0E01',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'vag_rain_closing_sunroof',
        nameKey: 'features.items.vag_rain_closing_sunroof.name',
        descKey: 'features.items.vag_rain_closing_sunroof.desc',
        defaultName: 'Rain Closing (Regenschließen)',
        defaultDesc: 'Automatically closes sunroof and windows when rain is detected while parked.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '709',
        didHex: '0E10',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 2. BMW / MINI (E, F, G Series)
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'bmw_start_stop_memory',
        nameKey: 'features.items.bmw_start_stop_memory.name',
        descKey: 'features.items.bmw_start_stop_memory.desc',
        defaultName: 'Auto Start-Stop Memory Mode',
        defaultDesc: 'Remembers last Auto Start-Stop state (OFF/ON) across vehicle restarts.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '760',
        didHex: '3001',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_digital_speedometer',
        nameKey: 'features.items.bmw_digital_speedometer.name',
        descKey: 'features.items.bmw_digital_speedometer.desc',
        defaultName: 'Digital Speedometer Display',
        defaultDesc: 'Adds instant digital speed numerical display option to cluster screen.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '760',
        didHex: '1020',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_sport_displays',
        nameKey: 'features.items.bmw_sport_displays.name',
        descKey: 'features.items.bmw_sport_displays.desc',
        defaultName: 'Sport Displays (HP & Nm Gauges)',
        defaultDesc: 'Enables live horsepower and torque dynamic dials in iDrive screen.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '760',
        didHex: '3000',
        byteIndex: 1,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_acoustic_lock_sound',
        nameKey: 'features.items.bmw_acoustic_lock_sound.name',
        descKey: 'features.items.bmw_acoustic_lock_sound.desc',
        defaultName: 'Acoustic Lock/Unlock Sound',
        defaultDesc: 'Emits alarm system chirps when locking or unlocking the vehicle.',
        make: 'BMW',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '760',
        didHex: '3020',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_mirror_fold_delay_zero',
        nameKey: 'features.items.bmw_mirror_fold_delay_zero.name',
        descKey: 'features.items.bmw_mirror_fold_delay_zero.desc',
        defaultName: 'Instant Mirror Folding (0.0s Delay)',
        defaultDesc: 'Folds side mirrors instantly upon lock button press without holding delay.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '760',
        didHex: '3110',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_tpms_tire_temperature',
        nameKey: 'features.items.bmw_tpms_tire_temperature.name',
        descKey: 'features.items.bmw_tpms_tire_temperature.desc',
        defaultName: 'Tire Pressure & Temperature Display',
        defaultDesc: 'Displays real-time tire temperature alongside pressure in TPMS screen.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '760',
        didHex: '3001',
        byteIndex: 2,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_alpina_cluster_theme',
        nameKey: 'features.items.bmw_alpina_cluster_theme.name',
        descKey: 'features.items.bmw_alpina_cluster_theme.desc',
        defaultName: 'Alpina Digital Dash Layout',
        defaultDesc: 'Applies blue Alpina signature theme to digital instrument cluster.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '760',
        didHex: '3007',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_video_in_motion',
        nameKey: 'features.items.bmw_video_in_motion.name',
        descKey: 'features.items.bmw_video_in_motion.desc',
        defaultName: 'Video In Motion (VIM)',
        defaultDesc: 'Unlocks USB video playback on iDrive screen while driving.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '760',
        didHex: '3000',
        byteIndex: 0,
        bitIndex: 7,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'HIGH',
        streetLegalNoteKey: 'features.legalDisclaimerVim'
    },
    {
        id: 'bmw_sport_plus_mode_unlock',
        nameKey: 'features.items.bmw_sport_plus_mode_unlock.name',
        descKey: 'features.items.bmw_sport_plus_mode_unlock.desc',
        defaultName: 'Sport+ Driving Mode Enable',
        defaultDesc: 'Enables Sport+ high-performance dynamic driving mode in DEC selector.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '760',
        didHex: '3200',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'bmw_launch_control_unlock',
        nameKey: 'features.items.bmw_launch_control_unlock.name',
        descKey: 'features.items.bmw_launch_control_unlock.desc',
        defaultName: 'Launch Control Unlock',
        defaultDesc: 'Unlocks factory launch control acceleration program in transmission ECU.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E8',
        didHex: '010C',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'HIGH'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 3. MERCEDES-BENZ
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'mercedes_amg_menu_unlock',
        nameKey: 'features.items.mercedes_amg_menu_unlock.name',
        descKey: 'features.items.mercedes_amg_menu_unlock.desc',
        defaultName: 'AMG Performance Telemetry Menu',
        defaultDesc: 'Displays AMG oil temp, transmission temp, lap timer, and G-meter.',
        make: 'Mercedes-Benz',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7C6',
        didHex: '0108',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'mercedes_agility_mode_enable',
        nameKey: 'features.items.mercedes_agility_mode_enable.name',
        descKey: 'features.items.mercedes_agility_mode_enable.desc',
        defaultName: 'Agility (A) Transmission Mode',
        defaultDesc: 'Unlocks ultra-responsive Agility shift program in 7G/9G-Tronic transmission.',
        make: 'Mercedes-Benz',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E0',
        didHex: '020B',
        byteIndex: 1,
        bitIndex: 4,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'mercedes_drl_brightness_boost',
        nameKey: 'features.items.mercedes_drl_brightness_boost.name',
        descKey: 'features.items.mercedes_drl_brightness_boost.desc',
        defaultName: 'Daytime Running Lights 100% Intensity',
        defaultDesc: 'Increases LED daytime running lights output to 100% full brightness.',
        make: 'Mercedes-Benz',
        category: 'LIGHTING',
        targetEcuHeader: '740',
        didHex: '1012',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'mercedes_alarm_lock_chirp',
        nameKey: 'features.items.mercedes_alarm_lock_chirp.name',
        descKey: 'features.items.mercedes_alarm_lock_chirp.desc',
        defaultName: 'Acoustic Locking Horn Chirp',
        defaultDesc: 'Emits short horn chirp notification when central locking is engaged.',
        make: 'Mercedes-Benz',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '7C6',
        didHex: '0201',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'mercedes_dpf_adblue_gauge',
        nameKey: 'features.items.mercedes_dpf_adblue_gauge.name',
        descKey: 'features.items.mercedes_dpf_adblue_gauge.desc',
        defaultName: 'DPF Soot & AdBlue Level Gauge',
        defaultDesc: 'Displays exact DPF soot mass percentage and remaining AdBlue range in IC.',
        make: 'Mercedes-Benz',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7E0',
        didHex: '0408',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'mercedes_ambient_64_multi_zone',
        nameKey: 'features.items.mercedes_ambient_64_multi_zone.name',
        descKey: 'features.items.mercedes_ambient_64_multi_zone.desc',
        defaultName: '64-Color Multi-Zone Ambient Profile',
        defaultDesc: 'Unlocks dynamic multi-zone color cycle animation in MBUX interior lighting.',
        make: 'Mercedes-Benz',
        category: 'LIGHTING',
        targetEcuHeader: '7C6',
        didHex: '0304',
        byteIndex: 1,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 4. RENAULT / DACIA / NISSAN
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'renault_trip_computer_enable',
        nameKey: 'features.items.renault_trip_computer_enable.name',
        descKey: 'features.items.renault_trip_computer_enable.desc',
        defaultName: 'Trip Computer Telemetry Activation',
        defaultDesc: 'Enables fuel consumption, remaining range, and average speed data on cluster screen.',
        make: 'Renault',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '743',
        didHex: '0101',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_external_temp_display',
        nameKey: 'features.items.renault_external_temp_display.name',
        descKey: 'features.items.renault_external_temp_display.desc',
        defaultName: 'Outside Air Temperature Display',
        defaultDesc: 'Displays real-time external ambient temperature reading on instrument cluster.',
        make: 'Renault',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '743',
        didHex: '0105',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_automatic_tailgate',
        nameKey: 'features.items.renault_automatic_tailgate.name',
        descKey: 'features.items.renault_automatic_tailgate.desc',
        defaultName: 'Key Fob Remote Trunk Release',
        defaultDesc: 'Allows unlocking and popping the tailgate via key fob trunk button press.',
        make: 'Renault',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '745',
        didHex: '0204',
        byteIndex: 1,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_alarm_chirp',
        nameKey: 'features.items.renault_alarm_chirp.name',
        descKey: 'features.items.renault_alarm_chirp.desc',
        defaultName: 'Locking Horn Chirp Confirmation',
        defaultDesc: 'Sounds a quick horn beep when locking doors with hands-free key card.',
        make: 'Renault',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '745',
        didHex: '0210',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_shift_indicator',
        nameKey: 'features.items.renault_shift_indicator.name',
        descKey: 'features.items.renault_shift_indicator.desc',
        defaultName: 'Gear Shift Indicator (GSI) Enable',
        defaultDesc: 'Displays upshift and downshift arrows for optimal fuel economy.',
        make: 'Renault',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '743',
        didHex: '010C',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_rs_monitor_enable',
        nameKey: 'features.items.renault_rs_monitor_enable.name',
        descKey: 'features.items.renault_rs_monitor_enable.desc',
        defaultName: 'Renault Sport RS Monitor Telemetry',
        defaultDesc: 'Enables live G-force, turbo boost, and oil temp telemetry on R-Link.',
        make: 'Renault',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '743',
        didHex: '0300',
        byteIndex: 0,
        bitIndex: 5,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_duster_mirror_fold',
        nameKey: 'features.items.renault_duster_mirror_fold.name',
        descKey: 'features.items.renault_duster_mirror_fold.desc',
        defaultName: 'Duster Auto Mirror Folding on Lock',
        defaultDesc: 'Folds side mirrors automatically via BCM central locking command.',
        make: 'Renault',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '745',
        didHex: '0402',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 5. FORD / LINCOLN
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'ford_bambi_mode_fog_light',
        nameKey: 'features.items.ford_bambi_mode_fog_light.name',
        descKey: 'features.items.ford_bambi_mode_fog_light.desc',
        defaultName: 'Bambi Mode (High Beams + Fog Lights)',
        defaultDesc: 'Allows fog lights to remain ON when high beam headlights are activated.',
        make: 'Ford',
        category: 'LIGHTING',
        targetEcuHeader: '726',
        didHex: '0425',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'ford_double_horn_honk_disable',
        nameKey: 'features.items.ford_double_horn_honk_disable.name',
        descKey: 'features.items.ford_double_horn_honk_disable.desc',
        defaultName: 'Disable Double Horn Honk on Door Close',
        defaultDesc: 'Disables double horn honk when closing door with engine running.',
        make: 'Ford',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '726',
        didHex: '0420',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'ford_auto_door_locking',
        nameKey: 'features.items.ford_auto_door_locking.name',
        descKey: 'features.items.ford_auto_door_locking.desc',
        defaultName: 'Auto Door Locking @ 20 km/h',
        defaultDesc: 'Automatically locks all doors when vehicle speed reaches 20 km/h.',
        make: 'Ford',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '726',
        didHex: '0112',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'ford_st_rs_boot_animation',
        nameKey: 'features.items.ford_st_rs_boot_animation.name',
        descKey: 'features.items.ford_st_rs_boot_animation.desc',
        defaultName: 'ST/RS Performance SYNC Boot Screen',
        defaultDesc: 'Changes SYNC touchscreen startup splash animation to ST / RS logo.',
        make: 'Ford',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7D0',
        didHex: '0101',
        byteIndex: 0,
        bitIndex: 4,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'ford_trailer_brake_activation',
        nameKey: 'features.items.ford_trailer_brake_activation.name',
        descKey: 'features.items.ford_trailer_brake_activation.desc',
        defaultName: 'Trailer Brake Controller (TBC) Enable',
        defaultDesc: 'Enables integrated trailer brake controller menu in instrument cluster.',
        make: 'Ford',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '720',
        didHex: 'D905',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 6. TOYOTA / LEXUS
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'toyota_reverse_beep_mute',
        nameKey: 'features.items.toyota_reverse_beep_mute.name',
        descKey: 'features.items.toyota_reverse_beep_mute.desc',
        defaultName: 'Reverse Gear Continuous Cabin Beep Mute',
        defaultDesc: 'Mutes continuous reverse gear chime inside cabin to a single beep.',
        make: 'Toyota',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '7C0',
        didHex: '0104',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'toyota_remote_window_drop',
        nameKey: 'features.items.toyota_remote_window_drop.name',
        descKey: 'features.items.toyota_remote_window_drop.desc',
        defaultName: 'Key Fob Remote Window Roll Down',
        defaultDesc: 'Rolls down all power windows when holding key fob unlock button.',
        make: 'Toyota',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '750',
        didHex: '0202',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'toyota_auto_lock_shift_p',
        nameKey: 'features.items.toyota_auto_lock_shift_p.name',
        descKey: 'features.items.toyota_auto_lock_shift_p.desc',
        defaultName: 'Auto Lock Doors on Gear Shift (P -> D)',
        defaultDesc: 'Automatically locks all doors when shifting out of Park position.',
        make: 'Toyota',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '750',
        didHex: '010B',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 7. STELLANTIS / FIAT / PEUGEOT / JEEP
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'stellantis_power_windows_remote',
        nameKey: 'features.items.stellantis_power_windows_remote.name',
        descKey: 'features.items.stellantis_power_windows_remote.desc',
        defaultName: 'Key Fob Remote Window Roll Up/Down',
        defaultDesc: 'Rolls up or down all power windows when holding lock/unlock buttons.',
        make: 'Fiat',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7A0',
        didHex: '0101',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'stellantis_cornering_fogs',
        nameKey: 'features.items.stellantis_cornering_fogs.name',
        descKey: 'features.items.stellantis_cornering_fogs.desc',
        defaultName: 'Cornering Fog Lights Enable',
        defaultDesc: 'Illuminates cornering fog lamp during low-speed turns.',
        make: 'Fiat',
        category: 'LIGHTING',
        targetEcuHeader: '7A0',
        didHex: '0204',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'peugeot_icockpit_theme_unlock',
        nameKey: 'features.items.peugeot_icockpit_theme_unlock.name',
        descKey: 'features.items.peugeot_icockpit_theme_unlock.desc',
        defaultName: 'Peugeot 3D i-Cockpit Performance Theme',
        defaultDesc: 'Unlocks Copper and Track Red color display themes on 3D digital cluster.',
        make: 'Fiat',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '764',
        didHex: '0108',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'jeep_offroad_pages_enable',
        nameKey: 'features.items.jeep_offroad_pages_enable.name',
        descKey: 'features.items.jeep_offroad_pages_enable.desc',
        defaultName: 'Jeep Uconnect Off-Road Pages',
        defaultDesc: 'Enables pitch/roll angle gauges, wheel articulation, and 4x4 lock status.',
        make: 'Fiat',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7A0',
        didHex: '0502',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 8. HYUNDAI / KIA / GENESIS
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'hyundai_smart_welcome_mirror',
        nameKey: 'features.items.hyundai_smart_welcome_mirror.name',
        descKey: 'features.items.hyundai_smart_welcome_mirror.desc',
        defaultName: 'Smart Key Approach Welcome Mirror Unfold',
        defaultDesc: 'Automatically unfolds side mirrors when approaching vehicle with smart key.',
        make: 'Hyundai',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7A0',
        didHex: '0103',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'hyundai_one_touch_turn_7_flashes',
        nameKey: 'features.items.hyundai_one_touch_turn_7_flashes.name',
        descKey: 'features.items.hyundai_one_touch_turn_7_flashes.desc',
        defaultName: 'One-Touch Lane Change Signal (7 Flashes)',
        defaultDesc: 'Sets one-touch lane change blinker duration to 7 flashes.',
        make: 'Hyundai',
        category: 'LIGHTING',
        targetEcuHeader: '7A0',
        didHex: '0204',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'hyundai_svm_camera_speed_extend',
        nameKey: 'features.items.hyundai_svm_camera_speed_extend.name',
        descKey: 'features.items.hyundai_svm_camera_speed_extend.desc',
        defaultName: '360° Surround Camera Speed Extension (20 km/h)',
        defaultDesc: 'Keeps 360-degree parking camera active up to 20 km/h forward speed.',
        make: 'Hyundai',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7A0',
        didHex: '0205',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'hyundai_n_performance_exhaust_flap',
        nameKey: 'features.items.hyundai_n_performance_exhaust_flap.name',
        descKey: 'features.items.hyundai_n_performance_exhaust_flap.desc',
        defaultName: 'N-Performance Exhaust Flap Default OPEN',
        defaultDesc: 'Sets active exhaust valve default position to OPEN on engine start.',
        make: 'Hyundai',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '7E8',
        didHex: '0310',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 9. GM / CHEVROLET / GMC / CADILLAC
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'gm_afm_dfm_cylinder_deactivation_disable',
        nameKey: 'features.items.gm_afm_dfm_cylinder_deactivation_disable.name',
        descKey: 'features.items.gm_afm_dfm_cylinder_deactivation_disable.desc',
        defaultName: 'AFM/DFM V8 Cylinder Lock (No V4 Drop)',
        defaultDesc: 'Locks engine in 8-cylinder mode permanently to prevent V4 vibration.',
        make: 'Chevrolet',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E8',
        didHex: '0101',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'gm_remote_start_time_extend',
        nameKey: 'features.items.gm_remote_start_time_extend.name',
        descKey: 'features.items.gm_remote_start_time_extend.desc',
        defaultName: 'Remote Start Duration Extension (20 Mins)',
        defaultDesc: 'Extends factory key fob remote engine start run time from 10 to 20 minutes.',
        make: 'Chevrolet',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '700',
        didHex: '0204',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 10. DODGE / RAM / JEEP / CHRYSLER
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'dodge_srt_performance_pages',
        nameKey: 'features.items.dodge_srt_performance_pages.name',
        descKey: 'features.items.dodge_srt_performance_pages.desc',
        defaultName: 'SRT Performance Pages & Drive Modes',
        defaultDesc: 'Unlocks Uconnect 0-100 acceleration timers, G-force meter, and launch control.',
        make: 'Dodge',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7A0',
        didHex: '0901',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'ram_bambi_mode_fog',
        nameKey: 'features.items.ram_bambi_mode_fog.name',
        descKey: 'features.items.ram_bambi_mode_fog.desc',
        defaultName: 'RAM Truck Fog Lights with High Beam',
        defaultDesc: 'Allows RAM fog lights to remain active alongside high beam headlights.',
        make: 'Dodge',
        category: 'LIGHTING',
        targetEcuHeader: '7A0',
        didHex: '0412',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 11. CHINESE BRANDS (BYD, MG / SAIC, CHERY, GEELY)
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'byd_avas_pedestrian_siren_mute',
        nameKey: 'features.items.byd_avas_pedestrian_siren_mute.name',
        descKey: 'features.items.byd_avas_pedestrian_siren_mute.desc',
        defaultName: 'AVAS EV Low-Speed Siren Mute',
        defaultDesc: 'Mutes low-speed artificial electric motor siren below 30 km/h.',
        make: 'BYD',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '7E0',
        didHex: '0102',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'chery_isa_overspeed_chime_mute',
        nameKey: 'features.items.chery_isa_overspeed_chime_mute.name',
        descKey: 'features.items.chery_isa_overspeed_chime_mute.desc',
        defaultName: 'ISA Overspeed Warning Chime Deactivation',
        defaultDesc: 'Disables continuous 80/120 km/h overspeed warning beep on Tiggo/MG models.',
        make: 'Chery',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '740',
        didHex: '0208',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'mg_ev_battery_preconditioning_toggle',
        nameKey: 'features.items.mg_ev_battery_preconditioning_toggle.name',
        descKey: 'features.items.mg_ev_battery_preconditioning_toggle.desc',
        defaultName: 'EV Fast-Charge Battery Pre-Heating Manual Switch',
        defaultDesc: 'Enables manual battery pre-heating switch before DC fast charging.',
        make: 'Chery',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E2',
        didHex: '0301',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'chery_dms_fatigue_camera_mute',
        nameKey: 'features.items.chery_dms_fatigue_camera_mute.name',
        descKey: 'features.items.chery_dms_fatigue_camera_mute.desc',
        defaultName: 'Driver Monitoring (DMS) Camera Sensitivity Reduction',
        defaultDesc: 'Reduces over-sensitive eye-tracking fatigue warnings on steering column.',
        make: 'Chery',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '740',
        didHex: '0405',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 12. JAPANESE BRANDS (HONDA, SUBARU)
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'honda_walk_away_auto_lock',
        nameKey: 'features.items.honda_walk_away_auto_lock.name',
        descKey: 'features.items.honda_walk_away_auto_lock.desc',
        defaultName: 'Walk-Away Auto Door Lock',
        defaultDesc: 'Automatically locks all doors when driver steps 2 meters away with key fob.',
        make: 'Toyota',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '750',
        didHex: '0302',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'subaru_avh_auto_hold_memory',
        nameKey: 'features.items.subaru_avh_auto_hold_memory.name',
        descKey: 'features.items.subaru_avh_auto_hold_memory.desc',
        defaultName: 'Auto Vehicle Hold (AVH) Memory Mode',
        defaultDesc: 'Remembers AVH brake hold ON/OFF state across ignition cycles.',
        make: 'Toyota',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E8',
        didHex: '0105',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 13. VOLVO / POLESTAR
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'volvo_start_stop_default_off',
        nameKey: 'features.items.volvo_start_stop_default_off.name',
        descKey: 'features.items.volvo_start_stop_default_off.desc',
        defaultName: 'Auto Start-Stop Default OFF Mode',
        defaultDesc: 'Sets Start-Stop engine shutoff system default state to OFF upon vehicle start.',
        make: 'Volvo',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '760',
        didHex: '0102',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'volvo_polestar_digital_theme',
        nameKey: 'features.items.volvo_polestar_digital_theme.name',
        descKey: 'features.items.volvo_polestar_digital_theme.desc',
        defaultName: 'Polestar Blue Digital Cluster Theme',
        defaultDesc: 'Unlocks Polestar signature blue dynamic gauge theme in Volvo driver display.',
        make: 'Volvo',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '760',
        didHex: '0208',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 14. VAG EXPANSION (MQB-Evo & MIB3)
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'vag_virtual_cockpit_r_theme',
        nameKey: 'features.items.vag_virtual_cockpit_r_theme.name',
        descKey: 'features.items.vag_virtual_cockpit_r_theme.desc',
        defaultName: 'Virtual Cockpit R / S / Cupra Performance Themes',
        defaultDesc: 'Unlocks R-Line, S-Line, and Cupra central tachometer performance themes in digital cockpit.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7C0',
        didHex: '0D0A',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'vag_sound_symposer_mute',
        nameKey: 'features.items.vag_sound_symposer_mute.name',
        descKey: 'features.items.vag_sound_symposer_mute.desc',
        defaultName: 'Sound Symposer Fake Engine Noise Deactivation',
        defaultDesc: 'Deactivates cabin speaker fake engine sound generator for pure exhaust note.',
        make: 'Volkswagen',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '7A9',
        didHex: '0101',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_wireless_carplay_enable',
        nameKey: 'features.items.vag_wireless_carplay_enable.name',
        descKey: 'features.items.vag_wireless_carplay_enable.desc',
        defaultName: 'Wireless Apple CarPlay & Android Auto Activation',
        defaultDesc: 'Enables 5GHz Wi-Fi wireless Apple CarPlay and Android Auto on MIB2.5/MIB3 units.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '75F',
        didHex: '12A0',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'vag_offroad_telemetry_menu',
        nameKey: 'features.items.vag_offroad_telemetry_menu.name',
        descKey: 'features.items.vag_offroad_telemetry_menu.desc',
        defaultName: 'MIB Offroad Telemetry & Gauge Display',
        defaultDesc: 'Displays steering angle, oil temp, coolant temp, and altitude gauges on MIB screen.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '75F',
        didHex: '09F1',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_easy_entry_driver_seat',
        nameKey: 'features.items.vag_easy_entry_driver_seat.name',
        descKey: 'features.items.vag_easy_entry_driver_seat.desc',
        defaultName: 'Automatic Easy Entry Power Seat Back-step',
        defaultDesc: 'Moves electric driver seat back 5 cm upon door opening for easy vehicle entry.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '736',
        didHex: '012B',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_hba_memory_state',
        nameKey: 'features.items.vag_hba_memory_state.name',
        descKey: 'features.items.vag_hba_memory_state.desc',
        defaultName: 'High-Beam Assist (HBA) Memory Retention',
        defaultDesc: 'Remembers High-Beam Assist ON status across ignition restart cycles.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '7A5',
        didHex: '0B14',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_battery_soc_display',
        nameKey: 'features.items.vag_battery_soc_display.name',
        descKey: 'features.items.vag_battery_soc_display.desc',
        defaultName: 'Battery State of Charge (% SOC) Display',
        defaultDesc: 'Shows exact battery charge percentage (% SOC) on instrument cluster when trip button is held.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7C0',
        didHex: '0210',
        byteIndex: 0,
        bitIndex: 4,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 15. BMW / MINI EXPANSION (G-Series & iDrive 7/8)
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'bmw_idrive7_m_animation',
        nameKey: 'features.items.bmw_idrive7_m_animation.name',
        descKey: 'features.items.bmw_idrive7_m_animation.desc',
        defaultName: 'iDrive 7 / 8 M-Performance Startup Animation',
        defaultDesc: 'Changes iDrive screen boot graphic to M-Performance or M-GmbH logo animation.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '63',
        didHex: '3001',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_bowers_wilkins_audio_profiles',
        nameKey: 'features.items.bmw_bowers_wilkins_audio_profiles.name',
        descKey: 'features.items.bmw_bowers_wilkins_audio_profiles.desc',
        defaultName: 'Bowers & Wilkins 3D Sound Engine Unlock',
        defaultDesc: 'Unlocks Bowers & Wilkins Concert, Studio, and Stage DSP audio profiles on HiFi systems.',
        make: 'BMW',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '63',
        didHex: '3005',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_hitch_zoom_camera',
        nameKey: 'features.items.bmw_hitch_zoom_camera.name',
        descKey: 'features.items.bmw_hitch_zoom_camera.desc',
        defaultName: 'Reverse Camera Trailer Hitch Zoom Mode',
        defaultDesc: 'Unlocks top-down trailer hitch alignment zoom mode on reverse camera view.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '63',
        didHex: '3009',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_secure_idle_protection',
        nameKey: 'features.items.bmw_secure_idle_protection.name',
        descKey: 'features.items.bmw_secure_idle_protection.desc',
        defaultName: 'Secure Idle Engine Shift-Lock Protection',
        defaultDesc: 'Locks transmission in Park if driver leaves running vehicle with key fob.',
        make: 'BMW',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '60',
        didHex: '3012',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_seatbelt_handover_mute',
        nameKey: 'features.items.bmw_seatbelt_handover_mute.name',
        descKey: 'features.items.bmw_seatbelt_handover_mute.desc',
        defaultName: 'Coupe Electric Seatbelt Handover Arm Deactivation',
        defaultDesc: 'Disables motorized seatbelt extender arm on 4 Series and 2 Series Coupes.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '60',
        didHex: '3015',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_auto_heat_threshold_5c',
        nameKey: 'features.items.bmw_auto_heat_threshold_5c.name',
        descKey: 'features.items.bmw_auto_heat_threshold_5c.desc',
        defaultName: 'Automatic Seat & Steering Wheel Heating Temperature (+5°C)',
        defaultDesc: 'Triggers automatic seat and steering wheel heating when ambient temp drops below 5°C.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '60',
        didHex: '3020',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 16. MERCEDES-BENZ EXPANSION (MBUX & W206/W214)
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'mercedes_amg_track_pace_unlock',
        nameKey: 'features.items.mercedes_amg_track_pace_unlock.name',
        descKey: 'features.items.mercedes_amg_track_pace_unlock.desc',
        defaultName: 'MBUX AMG Track Pace Telemetry & Lap Timer',
        defaultDesc: 'Unlocks lap timing, acceleration telemetry, and G-force graphs on MBUX screen.',
        make: 'Mercedes-Benz',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7E0',
        didHex: '0112',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'mercedes_drive_mode_last_memory',
        nameKey: 'features.items.mercedes_drive_mode_last_memory.name',
        descKey: 'features.items.mercedes_drive_mode_last_memory.desc',
        defaultName: 'Dynamic Select Last Drive Mode Memory',
        defaultDesc: 'Remembers last selected Drive Mode (Individual / Sport) across vehicle restart.',
        make: 'Mercedes-Benz',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E0',
        didHex: '0204',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'mercedes_proximity_360_camera_auto',
        nameKey: 'features.items.mercedes_proximity_360_camera_auto.name',
        descKey: 'features.items.mercedes_proximity_360_camera_auto.desc',
        defaultName: 'Proximity Sensor Auto 360° Camera View',
        defaultDesc: 'Automatically switches screen to 360 camera when front sensors detect obstacle < 50 cm.',
        make: 'Mercedes-Benz',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '7E0',
        didHex: '0308',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 17. FORD EXPANSION (SYNC4 & BCMii)
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'ford_sync_climate_screen_unlock',
        nameKey: 'features.items.ford_sync_climate_screen_unlock.name',
        descKey: 'features.items.ford_sync_climate_screen_unlock.desc',
        defaultName: 'SYNC3 / SYNC4 Touchscreen Climate Control Page',
        defaultDesc: 'Enables climate control, heated seat, and airflow direction touchscreen page.',
        make: 'Ford',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7D0',
        didHex: '0105',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'ford_turn_signal_5_flashes',
        nameKey: 'features.items.ford_turn_signal_5_flashes.name',
        descKey: 'features.items.ford_turn_signal_5_flashes.desc',
        defaultName: 'One-Touch Lane Change Signal (5 Flashes)',
        defaultDesc: 'Increases one-touch lane change turn signal duration from 3 to 5 flashes.',
        make: 'Ford',
        category: 'LIGHTING',
        targetEcuHeader: '726',
        didHex: '0109',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'ford_auto_engine_shutdown_disable',
        nameKey: 'features.items.ford_auto_engine_shutdown_disable.name',
        descKey: 'features.items.ford_auto_engine_shutdown_disable.desc',
        defaultName: '30-Minute Idle Auto Engine Shutdown Override',
        defaultDesc: 'Prevents automatic engine shutoff after 30 minutes idle (for camping/power outlet use).',
        make: 'Ford',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '720',
        didHex: '0202',
        byteIndex: 0,
        bitIndex: 4,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 18. ELECTRIC & CHINESE VEHICLES (BYD, CHERY, MG, HYUNDAI EV)
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'ev_battery_preheat_manual_switch',
        nameKey: 'features.items.ev_battery_preheat_manual_switch.name',
        descKey: 'features.items.ev_battery_preheat_manual_switch.desc',
        defaultName: 'EV Battery Pre-Heating Manual Switch (Fast DC Charge Prep)',
        defaultDesc: 'Allows manual battery pre-heating to 25°C before DC fast charging without navigation route.',
        make: 'BYD',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E2',
        didHex: '0108',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'ev_v2l_power_output_expand',
        nameKey: 'features.items.ev_v2l_power_output_expand.name',
        descKey: 'features.items.ev_v2l_power_output_expand.desc',
        defaultName: 'V2L (Vehicle-to-Load) 220V Outlet Power Expansion (3.6 kW)',
        defaultDesc: 'Expands V2L external 220V AC household power outlet limit from 2.2 kW to 3.6 kW.',
        make: 'BYD',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '7E4',
        didHex: '0204',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'ev_one_pedal_regen_force_level3',
        nameKey: 'features.items.ev_one_pedal_regen_force_level3.name',
        descKey: 'features.items.ev_one_pedal_regen_force_level3.desc',
        defaultName: 'One-Pedal Drive Maximum Regenerative Braking Default',
        defaultDesc: 'Sets maximum regenerative braking (One-Pedal stop mode) as default on vehicle start.',
        make: 'BYD',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E0',
        didHex: '0302',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },

    // ═════════════════════════════════════════════════════════════════════════
    // 19. ADVANCED EV & HYBRID (PHEV / HEV / BEV) EXPANSION
    // ═════════════════════════════════════════════════════════════════════════
    {
        id: 'byd_soc_max_charge_target_limit',
        nameKey: 'features.items.byd_soc_max_charge_target_limit.name',
        descKey: 'features.items.byd_soc_max_charge_target_limit.desc',
        defaultName: 'BYD Battery Health Protection Max Charge Limit (80% / 90%)',
        defaultDesc: 'Sets max AC/DC charge cutoff limit to 80% or 90% to extend Blade Battery lifespan.',
        make: 'BYD',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '7E2',
        didHex: '0110',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'byd_dmi_forced_pure_ev_speed_override',
        nameKey: 'features.items.byd_dmi_forced_pure_ev_speed_override.name',
        descKey: 'features.items.byd_dmi_forced_pure_ev_speed_override.desc',
        defaultName: 'BYD DM-i Pure EV Mode Gasoline Engine Override',
        defaultDesc: 'Inhibits gasoline engine start in EV mode up to 130 km/h even during full throttle acceleration.',
        make: 'BYD',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E0',
        didHex: '0301',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'byd_vtol_v2v_rescue_charge_mode',
        nameKey: 'features.items.byd_vtol_v2v_rescue_charge_mode.name',
        descKey: 'features.items.byd_vtol_v2v_rescue_charge_mode.desc',
        defaultName: 'BYD VTOL (Vehicle-to-Vehicle) Rescue Charge Mode',
        defaultDesc: 'Unlocks external AC power output to charge stranded electric vehicles on road.',
        make: 'BYD',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '7E4',
        didHex: '0402',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'hyundai_ipedal_memory_lock',
        nameKey: 'features.items.hyundai_ipedal_memory_lock.name',
        descKey: 'features.items.hyundai_ipedal_memory_lock.desc',
        defaultName: 'Hyundai / Kia i-PEDAL One-Pedal Drive Memory Lock',
        defaultDesc: 'Prevents i-PEDAL one-pedal stop mode from dropping back to Level 3 after shifting to Reverse.',
        make: 'Hyundai',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E0',
        didHex: '0105',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'hyundai_utility_mode_12v_saver',
        nameKey: 'features.items.hyundai_utility_mode_12v_saver.name',
        descKey: 'features.items.hyundai_utility_mode_12v_saver.desc',
        defaultName: 'Utility Camping Mode High-Voltage 12V Saver',
        defaultDesc: 'Powers 220V V2L outlet directly from HV traction battery to prevent auxiliary 12V battery drain.',
        make: 'Hyundai',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '7E4',
        didHex: '0215',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'hyundai_phev_no_ice_climate_start',
        nameKey: 'features.items.hyundai_phev_no_ice_climate_start.name',
        descKey: 'features.items.hyundai_phev_no_ice_climate_start.desc',
        defaultName: 'PHEV EV Mode Climate Heating Gasoline Engine Suppression',
        defaultDesc: 'Forces heat pump / PTC electric heater for cabin climate without starting gasoline engine.',
        make: 'Hyundai',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7B0',
        didHex: '0304',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_taycan_ess_sound_profile_swap',
        nameKey: 'features.items.vag_taycan_ess_sound_profile_swap.name',
        descKey: 'features.items.vag_taycan_ess_sound_profile_swap.desc',
        defaultName: 'Electric Sport Sound (ESS) Taycan / RS e-tron Profile',
        defaultDesc: 'Changes electric driving sound profile to Porsche Taycan GTS or Audi RS e-tron GT sound generator.',
        make: 'Volkswagen',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '7A9',
        didHex: '0101',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_meb_daily_charge_target_menu',
        nameKey: 'features.items.vag_meb_daily_charge_target_menu.name',
        descKey: 'features.items.vag_meb_daily_charge_target_menu.desc',
        defaultName: 'MEB Battery Daily 80% / Trip 100% Quick Charge Bar',
        defaultDesc: 'Adds quick toggle bar on MIB screen to switch between 80% daily battery care and 100% trip charge.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '78C',
        didHex: '0B02',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_gte_generator_charge_reserve',
        nameKey: 'features.items.vag_gte_generator_charge_reserve.name',
        descKey: 'features.items.vag_gte_generator_charge_reserve.desc',
        defaultName: 'GTE / E-Mode Engine Generator Battery Force Charge (80%)',
        defaultDesc: 'Forces combustion engine to act as generator to recharge high-voltage battery up to 80% while driving.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '78C',
        didHex: '0C10',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_hans_zimmer_iconic_sounds_m',
        nameKey: 'features.items.bmw_hans_zimmer_iconic_sounds_m.name',
        descKey: 'features.items.bmw_hans_zimmer_iconic_sounds_m.desc',
        defaultName: 'Hans Zimmer IconicSounds Electric M-Performance Sound Engine',
        defaultDesc: 'Unlocks Hans Zimmer acoustic M-Performance electric acceleration sound profiles on i4 and iX.',
        make: 'BMW',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '63',
        didHex: '3030',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_phev_max_edrive_140kmh',
        nameKey: 'features.items.bmw_phev_max_edrive_140kmh.name',
        descKey: 'features.items.bmw_phev_max_edrive_140kmh.desc',
        defaultName: 'PHEV MAX eDrive Pure Electric Speed Ceiling (140 km/h)',
        defaultDesc: 'Increases max pure electric speed ceiling on 330e / 530e Plug-in hybrids to 140 km/h.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '60',
        didHex: '3035',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_ac_charging_current_limit_menu',
        nameKey: 'features.items.bmw_ac_charging_current_limit_menu.name',
        descKey: 'features.items.bmw_ac_charging_current_limit_menu.desc',
        defaultName: 'AC Home Charger Maximum Current Limit Selector (6A - 32A)',
        defaultDesc: 'Adds AC home charging current limiter (6A / 10A / 16A / 32A) to prevent home circuit overload.',
        make: 'BMW',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '63',
        didHex: '3040',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'toyota_hybrid_ev_mode_override',
        nameKey: 'features.items.toyota_hybrid_ev_mode_override.name',
        descKey: 'features.items.toyota_hybrid_ev_mode_override.desc',
        defaultName: 'Toyota / Lexus EV Mode Throttle Override Suppression',
        defaultDesc: 'Prevents gasoline engine from forced start during acceleration when EV mode button is active.',
        make: 'Toyota',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E0',
        didHex: '0101',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'toyota_hybrid_battery_fan_speed_boost',
        nameKey: 'features.items.toyota_hybrid_battery_fan_speed_boost.name',
        descKey: 'features.items.toyota_hybrid_battery_fan_speed_boost.desc',
        defaultName: 'Toyota / Lexus High-Voltage Battery Cooling Fan Boost (+30%)',
        defaultDesc: 'Increases hybrid traction battery cooling fan speed by +30% to prevent thermal degradation in hot climates.',
        make: 'Toyota',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '7E0',
        didHex: '0205',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'tesla_sentry_high_bitrate_video',
        nameKey: 'features.items.tesla_sentry_high_bitrate_video.name',
        descKey: 'features.items.tesla_sentry_high_bitrate_video.desc',
        defaultName: 'Tesla Sentry Mode High-Bitrate Continuous Dashcam Recording',
        defaultDesc: 'Increases Sentry Mode camera video recording bitrate for crystal-clear license plate visibility.',
        make: 'Tesla',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '7E0',
        didHex: '0101',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'tesla_cabin_overheat_threshold_30c',
        nameKey: 'features.items.tesla_cabin_overheat_threshold_30c.name',
        descKey: 'features.items.tesla_cabin_overheat_threshold_30c.desc',
        defaultName: 'Tesla Cabin Overheat Protection Temperature Threshold (30°C)',
        defaultDesc: 'Lowers cabin overheat protection climate trigger temperature from 40°C to 30°C for interior preservation.',
        make: 'Tesla',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7E0',
        didHex: '0202',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    }
];

export class OemDatabaseProvider {
    private features: Map<string, OEMFeatureDefinition> = new Map();

    constructor() {
        for (const feat of EXTENDED_OEM_FEATURES) {
            this.features.set(feat.id, feat);
        }
    }

    /**
     * Retrieves all available features filtered by vehicle make and optional category.
     */
    public getFeaturesForMake(make?: string, category?: FeatureCategory | 'ALL'): OEMFeatureDefinition[] {
        let list = Array.from(this.features.values());

        if (make && make !== 'ALL') {
            const cleanMake = make.toUpperCase();
            list = list.filter(f => f.make.toUpperCase().includes(cleanMake) || cleanMake.includes(f.make.toUpperCase()));
        }

        if (category && category !== 'ALL') {
            list = list.filter(f => f.category === category);
        }

        return list;
    }

    /**
     * Retrieves a specific feature definition by ID.
     */
    public getFeatureById(id: string): OEMFeatureDefinition | undefined {
        return this.features.get(id);
    }

    /**
     * Returns total count of registered OEM features.
     */
    public getTotalFeatureCount(): number {
        return this.features.size;
    }
}

export const oemDatabaseProvider = new OemDatabaseProvider();
