/**
 * BmwProfile.ts — BMW, MINI & Rolls-Royce OEM Feature Activation Profile
 * Supports E, F, G, I-Series (FEM, BDC, CAS, KOMBI, HU_NBT/MGU, IHKA).
 */

import { OEMFeatureDefinition } from '../types';

export const BMW_OEM_FEATURES: OEMFeatureDefinition[] = [
    {
        id: 'bmw_oil_service_reset',
        nameKey: 'features.items.bmw_oil_service_reset.name',
        descKey: 'features.items.bmw_oil_service_reset.desc',
        defaultName: 'CBS Engine Oil Reset',
        defaultDesc: 'Resets Condition Based Service (CBS) oil life percentage back to 100%.',
        make: 'BMW',
        category: 'SERVICE_MAINTENANCE',
        targetEcuHeader: '60',
        didHex: '1000',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_video_in_motion_speedlock',
        nameKey: 'features.items.bmw_video_in_motion_speedlock.name',
        descKey: 'features.items.bmw_video_in_motion_speedlock.desc',
        defaultName: 'Video in Motion (VIM) Speedlock Removal',
        defaultDesc: 'Allows USB and DVD video playback on iDrive screen while vehicle is moving.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '63',
        didHex: '3000',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_digital_speedo_kombi',
        nameKey: 'features.items.bmw_digital_speedo_kombi.name',
        descKey: 'features.items.bmw_digital_speedo_kombi.desc',
        defaultName: 'Digital Speedometer in Instrument Cluster',
        defaultDesc: 'Adds real-time digital speed numerical readout on the onboard computer screen.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '60',
        didHex: '3001',
        byteIndex: 1,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_start_stop_memory',
        nameKey: 'features.items.bmw_start_stop_memory.name',
        descKey: 'features.items.bmw_start_stop_memory.desc',
        defaultName: 'Auto Start-Stop Function Memory',
        defaultDesc: 'Remembers the last state of the Auto Start-Stop button instead of resetting to ON at start.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '40',
        didHex: '3002',
        byteIndex: 0,
        bitIndex: 4,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_acoustic_lock_chirp',
        nameKey: 'features.items.bmw_acoustic_lock_chirp.name',
        descKey: 'features.items.bmw_acoustic_lock_chirp.desc',
        defaultName: 'Acoustic Alarm Chirp on Lock / Unlock',
        defaultDesc: 'Adds acoustic confirmation chirp via alarm siren with volume setting in iDrive menu.',
        make: 'BMW',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '40',
        didHex: '3003',
        byteIndex: 2,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_auto_mirror_fold_comfort_close',
        nameKey: 'features.items.bmw_auto_mirror_fold_comfort_close.name',
        descKey: 'features.items.bmw_auto_mirror_fold_comfort_close.desc',
        defaultName: 'Fold Mirrors Instantly with 1-Click Lock',
        defaultDesc: 'Eliminates the 1.5s delay requirement for folding mirrors when pressing key lock.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '40',
        didHex: '3004',
        byteIndex: 0,
        bitIndex: 6,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_rolls_royce_warning_chimes',
        nameKey: 'features.items.bmw_rolls_royce_warning_chimes.name',
        descKey: 'features.items.bmw_rolls_royce_warning_chimes.desc',
        defaultName: 'Rolls-Royce / BMW i / MINI Warning Chime Tones',
        defaultDesc: 'Changes the system warning chimes (door open, low temp, seatbelt) to luxury Rolls-Royce tones.',
        make: 'BMW',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '63',
        didHex: '3005',
        byteIndex: 3,
        bitIndex: 0,
        options: [
            { labelKey: 'features.options.chimeBmw', defaultLabel: 'BMW Standard', valueHex: '00' },
            { labelKey: 'features.options.chimeMini', defaultLabel: 'MINI Style', valueHex: '01' },
            { labelKey: 'features.options.chimeRolls', defaultLabel: 'Rolls-Royce Luxury', valueHex: '02' },
            { labelKey: 'features.options.chimeBmwi', defaultLabel: 'BMW i Electric', valueHex: '03' }
        ],
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_m_performance_boot_animation',
        nameKey: 'features.items.bmw_m_performance_boot_animation.name',
        descKey: 'features.items.bmw_m_performance_boot_animation.desc',
        defaultName: 'M Performance / Alpina Cluster Boot Logo',
        defaultDesc: 'Sets startup logo on digital instrument cluster to M Performance, M2, M3, M5, or Alpina.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '60',
        didHex: '3006',
        byteIndex: 4,
        bitIndex: 0,
        options: [
            { labelKey: 'features.options.logoStandard', defaultLabel: 'BMW Standard', valueHex: '00' },
            { labelKey: 'features.options.logoMPerf', defaultLabel: 'M Performance', valueHex: '01' },
            { labelKey: 'features.options.logoAlpina', defaultLabel: 'Alpina Blue', valueHex: '02' }
        ],
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_tpms_temperature_display',
        nameKey: 'features.items.bmw_tpms_temperature_display.name',
        descKey: 'features.items.bmw_tpms_temperature_display.desc',
        defaultName: 'Tire Pressure & Temperature Live Display',
        defaultDesc: 'Adds real-time individual tire temperature readouts alongside tire pressure on iDrive screen.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '63',
        didHex: '3007',
        byteIndex: 1,
        bitIndex: 7,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_rear_drl_scandinavian',
        nameKey: 'features.items.bmw_rear_drl_scandinavian.name',
        descKey: 'features.items.bmw_rear_drl_scandinavian.desc',
        defaultName: 'Rear Tail Lights Active with Daytime Running Lights',
        defaultDesc: 'Keeps rear LED neon rings illuminated when daytime running lights are active in position 0/Auto.',
        make: 'BMW',
        category: 'LIGHTING',
        targetEcuHeader: '40',
        didHex: '3008',
        byteIndex: 5,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_sport_automatic_transmission_2tb',
        nameKey: 'features.items.bmw_sport_automatic_transmission_2tb.name',
        descKey: 'features.items.bmw_sport_automatic_transmission_2tb.desc',
        defaultName: 'Sport Automatic Transmission (2TB) & Launch Control',
        defaultDesc: 'Unlocks faster shifting times, rev-matching downshifts, and factory Launch Control mode.',
        make: 'BMW',
        category: 'PERFORMANCE',
        targetEcuHeader: '12',
        didHex: '3009',
        byteIndex: 2,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'bmw_easy_entry_exit_seat',
        nameKey: 'features.items.bmw_easy_entry_exit_seat.name',
        descKey: 'features.items.bmw_easy_entry_exit_seat.desc',
        defaultName: 'Easy Entry / Exit Seat Motion',
        defaultDesc: 'Moves electric driver seat backwards when opening door and returns to drive position upon engine start.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '6D',
        didHex: '3015',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_bowers_wilkins_sound_profiles',
        nameKey: 'features.items.bmw_bowers_wilkins_sound_profiles.name',
        descKey: 'features.items.bmw_bowers_wilkins_sound_profiles.desc',
        defaultName: 'Bowers & Wilkins High-End Sound Profiles',
        defaultDesc: 'Enables Studio, Concert, On Stage, and Lounge audio surround profiles on factory Harman Kardon sound systems.',
        make: 'BMW',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '763',
        didHex: '3000',
        byteIndex: 1,
        bitIndex: 4,
        requiresSecurityAccess: false,
        requiresExtendedSession: false,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_fog_lights_with_high_beams',
        nameKey: 'features.items.bmw_fog_lights_with_high_beams.name',
        descKey: 'features.items.bmw_fog_lights_with_high_beams.desc',
        defaultName: 'Fog Lights Active with High Beams',
        defaultDesc: 'Keeps front fog lights illuminated when flashing or turning on high beam headlights.',
        make: 'BMW',
        category: 'LIGHTING',
        targetEcuHeader: '7C0',
        didHex: '3060',
        byteIndex: 2,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_alpina_instrument_cluster',
        nameKey: 'features.items.bmw_alpina_instrument_cluster.name',
        descKey: 'features.items.bmw_alpina_instrument_cluster.desc',
        defaultName: 'Alpina Blue Instrument Cluster Display',
        defaultDesc: 'Switches digital instrument cluster theme to classic Alpina signature blue dials and green needles.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '760',
        didHex: '3005',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_angel_eyes_brightness_max',
        nameKey: 'features.items.bmw_angel_eyes_brightness_max.name',
        descKey: 'features.items.bmw_angel_eyes_brightness_max.desc',
        defaultName: 'Angel Eyes Full DRL Brightness (100%)',
        defaultDesc: 'Forces corona ring Angel Eyes LED halo brightness to 100% duty cycle in low beam parking light mode.',
        make: 'BMW',
        category: 'LIGHTING',
        targetEcuHeader: '7C0',
        didHex: '3062',
        byteIndex: 0,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.drl50', defaultLabel: '50% (Factory)', valueHex: '32' },
            { labelKey: 'features.options.drl80', defaultLabel: '80%', valueHex: '50' },
            { labelKey: 'features.options.drl100', defaultLabel: '100% (Maximum Glow)', valueHex: '64' }
        ],
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_custom_dual_ambient_lighting',
        nameKey: 'features.items.bmw_custom_dual_ambient_lighting.name',
        descKey: 'features.items.bmw_custom_dual_ambient_lighting.desc',
        defaultName: 'Dual-Color Custom Ambient Lighting',
        defaultDesc: 'Splits dashboard and footwell ambient lighting into custom dual colors (Cyan upper / Orange lower).',
        make: 'BMW',
        category: 'LIGHTING',
        targetEcuHeader: '7C0',
        didHex: '3070',
        byteIndex: 4,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_tailgate_close_single_click',
        nameKey: 'features.items.bmw_tailgate_close_single_click.name',
        descKey: 'features.items.bmw_tailgate_close_single_click.desc',
        defaultName: 'Electric Tailgate Remote Single-Click Close',
        defaultDesc: 'Closes motorized rear liftgate with a single short press of key fob trunk button without continuous hold.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '764',
        didHex: '3010',
        byteIndex: 1,
        bitIndex: 5,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_window_up_door_open_continue',
        nameKey: 'features.items.bmw_window_up_door_open_continue.name',
        descKey: 'features.items.bmw_window_up_door_open_continue.desc',
        defaultName: 'Continuous Window Roll-Up with Door Open',
        defaultDesc: 'Allows power windows to complete one-touch closing cycle even if a vehicle door is opened.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7C0',
        didHex: '3020',
        byteIndex: 3,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_trailer_camera_zoom_mode',
        nameKey: 'features.items.bmw_trailer_camera_zoom_mode.name',
        descKey: 'features.items.bmw_trailer_camera_zoom_mode.desc',
        defaultName: 'Trailer Hitch Camera Zoom View',
        defaultDesc: 'Adds dedicated top-down zoom button to rear camera screen for precise tow bar and trailer alignment.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '763',
        didHex: '3002',
        byteIndex: 0,
        bitIndex: 6,
        requiresSecurityAccess: false,
        requiresExtendedSession: false,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_sport_displays_power_units',
        nameKey: 'features.items.bmw_sport_displays_power_units.name',
        descKey: 'features.items.bmw_sport_displays_power_units.desc',
        defaultName: 'Sport Displays HP & Nm Units',
        defaultDesc: 'Switches digital live engine telemetry gauges on iDrive display to Horsepower (hp) and Torque (Nm).',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '763',
        didHex: '3008',
        byteIndex: 2,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: false,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_ac_last_state_memory',
        nameKey: 'features.items.bmw_ac_last_state_memory.name',
        descKey: 'features.items.bmw_ac_last_state_memory.desc',
        defaultName: 'Air Conditioning Last State Memory',
        defaultDesc: 'Prevents air conditioning compressor from automatically activating on every vehicle start.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '762',
        didHex: '3001',
        byteIndex: 0,
        bitIndex: 4,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_mirror_fold_instant_close',
        nameKey: 'features.items.bmw_mirror_fold_instant_close.name',
        descKey: 'features.items.bmw_mirror_fold_instant_close.desc',
        defaultName: 'Instant Mirror Fold Delay Elimination (0.0s)',
        defaultDesc: 'Folds side view mirrors instantly upon single key fob lock press by setting comfort close delay to 0 ms.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '7C0',
        didHex: '3055',
        byteIndex: 0,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.delay0ms', defaultLabel: '0.0s (Instant)', valueHex: '00' },
            { labelKey: 'features.options.delay500ms', defaultLabel: '0.5s', valueHex: '05' },
            { labelKey: 'features.options.delay1500ms', defaultLabel: '1.5s (Factory)', valueHex: '0F' }
        ],
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    }
];

