/**
 * BmwProfile.ts — BMW, MINI & Rolls-Royce OEM Feature Activation Profile
 * Supports E, F, G, I-Series (FEM, BDC, CAS, KOMBI, HU_NBT/MGU, IHKA).
 */

import { OEMFeatureDefinition } from '../types';

export const BMW_OEM_FEATURES: OEMFeatureDefinition[] = [
    {
        id: 'bmw_oil_service_reset',
        nameKey: 'features.items.bmw_oil_service_reset.name',
        descKey: 'features.items.bmw_oil_service_reset.desc',
        defaultName: 'CBS Engine Oil Reset',
        defaultDesc: 'Resets Condition Based Service (CBS) oil life percentage back to 100%.',
        make: 'BMW',
        category: 'SERVICE_MAINTENANCE',
        targetEcuHeader: '60',
        didHex: '1000',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_video_in_motion_speedlock',
        nameKey: 'features.items.bmw_video_in_motion_speedlock.name',
        descKey: 'features.items.bmw_video_in_motion_speedlock.desc',
        defaultName: 'Video in Motion (VIM) Speedlock Removal',
        defaultDesc: 'Allows USB and DVD video playback on iDrive screen while vehicle is moving.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '63',
        didHex: '3000',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_digital_speedo_kombi',
        nameKey: 'features.items.bmw_digital_speedo_kombi.name',
        descKey: 'features.items.bmw_digital_speedo_kombi.desc',
        defaultName: 'Digital Speedometer in Instrument Cluster',
        defaultDesc: 'Adds real-time digital speed numerical readout on the onboard computer screen.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '60',
        didHex: '3001',
        byteIndex: 1,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_start_stop_memory',
        nameKey: 'features.items.bmw_start_stop_memory.name',
        descKey: 'features.items.bmw_start_stop_memory.desc',
        defaultName: 'Auto Start-Stop Function Memory',
        defaultDesc: 'Remembers the last state of the Auto Start-Stop button instead of resetting to ON at start.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '40',
        didHex: '3002',
        byteIndex: 0,
        bitIndex: 4,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_acoustic_lock_chirp',
        nameKey: 'features.items.bmw_acoustic_lock_chirp.name',
        descKey: 'features.items.bmw_acoustic_lock_chirp.desc',
        defaultName: 'Acoustic Alarm Chirp on Lock / Unlock',
        defaultDesc: 'Adds acoustic confirmation chirp via alarm siren with volume setting in iDrive menu.',
        make: 'BMW',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '40',
        didHex: '3003',
        byteIndex: 2,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_auto_mirror_fold_comfort_close',
        nameKey: 'features.items.bmw_auto_mirror_fold_comfort_close.name',
        descKey: 'features.items.bmw_auto_mirror_fold_comfort_close.desc',
        defaultName: 'Fold Mirrors Instantly with 1-Click Lock',
        defaultDesc: 'Eliminates the 1.5s delay requirement for folding mirrors when pressing key lock.',
        make: 'BMW',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '40',
        didHex: '3004',
        byteIndex: 0,
        bitIndex: 6,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_rolls_royce_warning_chimes',
        nameKey: 'features.items.bmw_rolls_royce_warning_chimes.name',
        descKey: 'features.items.bmw_rolls_royce_warning_chimes.desc',
        defaultName: 'Rolls-Royce / BMW i / MINI Warning Chime Tones',
        defaultDesc: 'Changes the system warning chimes (door open, low temp, seatbelt) to luxury Rolls-Royce tones.',
        make: 'BMW',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '63',
        didHex: '3005',
        byteIndex: 3,
        bitIndex: 0,
        options: [
            { labelKey: 'features.options.chimeBmw', defaultLabel: 'BMW Standard', valueHex: '00' },
            { labelKey: 'features.options.chimeMini', defaultLabel: 'MINI Style', valueHex: '01' },
            { labelKey: 'features.options.chimeRolls', defaultLabel: 'Rolls-Royce Luxury', valueHex: '02' },
            { labelKey: 'features.options.chimeBmwi', defaultLabel: 'BMW i Electric', valueHex: '03' }
        ],
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_m_performance_boot_animation',
        nameKey: 'features.items.bmw_m_performance_boot_animation.name',
        descKey: 'features.items.bmw_m_performance_boot_animation.desc',
        defaultName: 'M Performance / Alpina Cluster Boot Logo',
        defaultDesc: 'Sets startup logo on digital instrument cluster to M Performance, M2, M3, M5, or Alpina.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '60',
        didHex: '3006',
        byteIndex: 4,
        bitIndex: 0,
        options: [
            { labelKey: 'features.options.logoStandard', defaultLabel: 'BMW Standard', valueHex: '00' },
            { labelKey: 'features.options.logoMPerf', defaultLabel: 'M Performance', valueHex: '01' },
            { labelKey: 'features.options.logoAlpina', defaultLabel: 'Alpina Blue', valueHex: '02' }
        ],
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_tpms_temperature_display',
        nameKey: 'features.items.bmw_tpms_temperature_display.name',
        descKey: 'features.items.bmw_tpms_temperature_display.desc',
        defaultName: 'Tire Pressure & Temperature Live Display',
        defaultDesc: 'Adds real-time individual tire temperature readouts alongside tire pressure on iDrive screen.',
        make: 'BMW',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '63',
        didHex: '3007',
        byteIndex: 1,
        bitIndex: 7,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_rear_drl_scandinavian',
        nameKey: 'features.items.bmw_rear_drl_scandinavian.name',
        descKey: 'features.items.bmw_rear_drl_scandinavian.desc',
        defaultName: 'Rear Tail Lights Active with Daytime Running Lights',
        defaultDesc: 'Keeps rear LED neon rings illuminated when daytime running lights are active in position 0/Auto.',
        make: 'BMW',
        category: 'LIGHTING',
        targetEcuHeader: '40',
        didHex: '3008',
        byteIndex: 5,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'bmw_sport_automatic_transmission_2tb',
        nameKey: 'features.items.bmw_sport_automatic_transmission_2tb.name',
        descKey: 'features.items.bmw_sport_automatic_transmission_2tb.desc',
        defaultName: 'Sport Automatic Transmission (2TB) & Launch Control',
        defaultDesc: 'Unlocks faster shifting times, rev-matching downshifts, and factory Launch Control mode.',
        make: 'BMW',
        category: 'PERFORMANCE',
        targetEcuHeader: '12',
        didHex: '3009',
        byteIndex: 2,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    }
];
