/**
 * MercedesProfile.ts — Mercedes-Benz & AMG OEM Feature Activation Catalog
 * Supports NTG5, NTG6, MBUX, SAM, EZS, and Instrument Cluster modules.
 */

import { OEMFeatureDefinition } from '../types';

export const MERCEDES_OEM_FEATURES: OEMFeatureDefinition[] = [
    {
        id: 'merc_needle_sweep_staging',
        nameKey: 'features.items.merc_needle_sweep_staging.name',
        descKey: 'features.items.merc_needle_sweep_staging.desc',
        defaultName: 'Instrument Needle Sweep',
        defaultDesc: 'Sweeps gauge needles to maximum upon turning on the ignition.',
        make: 'Mercedes-Benz',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '2F',
        didHex: '0100',
        byteIndex: 1,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'merc_highbeam_memory',
        nameKey: 'features.items.merc_highbeam_memory.name',
        descKey: 'features.items.merc_highbeam_memory.desc',
        defaultName: 'High-Beam Assist State Memory',
        defaultDesc: 'Remembers the last active state of Adaptive Highbeam Assist across ignition cycles.',
        make: 'Mercedes-Benz',
        category: 'LIGHTING',
        targetEcuHeader: '5F',
        didHex: '02A0',
        byteIndex: 2,
        bitIndex: 4,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'merc_acoustic_lock_chirp',
        nameKey: 'features.items.merc_acoustic_lock_chirp.name',
        descKey: 'features.items.merc_acoustic_lock_chirp.desc',
        defaultName: 'Acoustic Alarm Lock Chirp',
        defaultDesc: 'Emits a short acoustic confirmation beep via alarm siren when vehicle is locked.',
        make: 'Mercedes-Benz',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '09',
        didHex: '0310',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'merc_amg_cluster_menu_unlock',
        nameKey: 'features.items.merc_amg_cluster_menu_unlock.name',
        descKey: 'features.items.merc_amg_cluster_menu_unlock.desc',
        defaultName: 'AMG Performance Cluster Menu & Oil Temp',
        defaultDesc: 'Unlocks AMG performance screen displaying engine oil & gearbox temperature, lap timer, and G-meter.',
        make: 'Mercedes-Benz',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '2F',
        didHex: '0450',
        byteIndex: 3,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'merc_ambient_lighting_64_colors',
        nameKey: 'features.items.merc_ambient_lighting_64_colors.name',
        descKey: 'features.items.merc_ambient_lighting_64_colors.desc',
        defaultName: '64-Color Dynamic Ambient Lighting Unlock',
        defaultDesc: 'Expands ambient lighting color palette from standard colors to 64 multi-color dynamic themes in MBUX.',
        make: 'Mercedes-Benz',
        category: 'LIGHTING',
        targetEcuHeader: '5F',
        didHex: '0520',
        byteIndex: 4,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'merc_start_stop_last_state_memory',
        nameKey: 'features.items.merc_start_stop_last_state_memory.name',
        descKey: 'features.items.merc_start_stop_last_state_memory.desc',
        defaultName: 'ECO Start-Stop Last State Memory',
        defaultDesc: 'Remembers ECO Start/Stop button status instead of defaulting to ON on every ignition restart.',
        make: 'Mercedes-Benz',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '01',
        didHex: '0680',
        byteIndex: 1,
        bitIndex: 7,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'merc_auto_mirror_fold_lock',
        nameKey: 'features.items.merc_auto_mirror_fold_lock.name',
        descKey: 'features.items.merc_auto_mirror_fold_lock.desc',
        defaultName: 'Automatic Mirror Folding on Key Lock',
        defaultDesc: 'Automatically folds side mirrors when locking with key fob and unfolds upon driver door open.',
        make: 'Mercedes-Benz',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '42',
        didHex: '0710',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: false,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'merc_rear_drl_scandinavian',
        nameKey: 'features.items.merc_rear_drl_scandinavian.name',
        descKey: 'features.items.merc_rear_drl_scandinavian.desc',
        defaultName: 'Rear Tail Lights as Daytime Running Lights',
        defaultDesc: 'Keeps rear LED tail lamps illuminated together with front DRLs during daytime driving.',
        make: 'Mercedes-Benz',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0840',
        byteIndex: 5,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'merc_seatbelt_warning_chime_mute',
        nameKey: 'features.items.merc_seatbelt_warning_chime_mute.name',
        descKey: 'features.items.merc_seatbelt_warning_chime_mute.desc',
        defaultName: 'Seatbelt Acoustic Warning Chime Mute',
        defaultDesc: 'Disables the continuous chime sound for unbuckled seatbelts (visual warning lamp remains active).',
        make: 'Mercedes-Benz',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '2F',
        didHex: '0910',
        byteIndex: 0,
        bitIndex: 6,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'merc_agility_manual_mode_unlock',
        nameKey: 'features.items.merc_agility_manual_mode_unlock.name',
        descKey: 'features.items.merc_agility_manual_mode_unlock.desc',
        defaultName: 'Agility (Sport+) & Manual Transmission Mode',
        defaultDesc: 'Enables hidden Agility (A) and True Manual (M) driving transmission profiles in Dynamic Select.',
        make: 'Mercedes-Benz',
        category: 'PERFORMANCE',
        targetEcuHeader: '02',
        didHex: '0A30',
        byteIndex: 2,
        bitIndex: 5,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'merc_esp_sport_threshold_tuning',
        nameKey: 'features.items.merc_esp_sport_threshold_tuning.name',
        descKey: 'features.items.merc_esp_sport_threshold_tuning.desc',
        defaultName: 'ESP Sport Dynamic Slip Angle Adjustment',
        defaultDesc: 'Allows increased wheel slip angle before ESP torque intervention for track driving.',
        make: 'Mercedes-Benz',
        category: 'PERFORMANCE',
        targetEcuHeader: '03',
        didHex: '0B20',
        byteIndex: 1,
        bitIndex: 4,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'merc_flashing_emergency_brake_light',
        nameKey: 'features.items.merc_flashing_emergency_brake_light.name',
        descKey: 'features.items.merc_flashing_emergency_brake_light.desc',
        defaultName: 'Adaptive Emergency Flashing Brake Lights',
        defaultDesc: 'Flashes stop lamps at high frequency (5.5 Hz) during hard emergency braking (> 7 m/s²).',
        make: 'Mercedes-Benz',
        category: 'SECURITY_SAFETY',
        targetEcuHeader: '09',
        didHex: '0C10',
        byteIndex: 4,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    }
];
