/**
 * RenaultProfile.ts — Renault & Dacia OEM Feature Activation Profile
 * Supports Clio, Megane, Captur, Kadjar, Talisman, Arkana, Dacia Duster, Sandero.
 */

import { OEMFeatureDefinition } from '../types';

export const RENAULT_OEM_FEATURES: OEMFeatureDefinition[] = [
    {
        id: 'renault_rlink_video_in_motion',
        nameKey: 'features.items.renault_rlink_video_in_motion.name',
        descKey: 'features.items.renault_rlink_video_in_motion.desc',
        defaultName: 'Video in Motion (VIM) Playback Unlock',
        defaultDesc: 'Allows USB/video playback on R-Link 2 / EasyLink touchscreen while vehicle is in motion.',
        make: 'Renault',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '5F',
        didHex: '3010',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_rs_monitor_telemetry_unlock',
        nameKey: 'features.items.renault_rs_monitor_telemetry_unlock.name',
        descKey: 'features.items.renault_rs_monitor_telemetry_unlock.desc',
        defaultName: 'RS Monitor Performance Telemetry App',
        defaultDesc: 'Enables Renault Sport Monitor app displaying live turbo boost, torque, oil temp, and G-force meters.',
        make: 'Renault',
        category: 'PERFORMANCE',
        targetEcuHeader: '5F',
        didHex: '3020',
        byteIndex: 1,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_acoustic_lock_chirp',
        nameKey: 'features.items.renault_acoustic_lock_chirp.name',
        descKey: 'features.items.renault_acoustic_lock_chirp.desc',
        defaultName: 'Acoustic Horn Chirp on Hands-Free Walkaway Lock',
        defaultDesc: 'Emits a brief beep when vehicle automatically locks upon walking away with key card.',
        make: 'Renault',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '09',
        didHex: '3030',
        byteIndex: 2,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_rear_scandinavian_drl',
        nameKey: 'features.items.renault_rear_scandinavian_drl.name',
        descKey: 'features.items.renault_rear_scandinavian_drl.desc',
        defaultName: 'Scandinavian Daytime Running Tail Lights',
        defaultDesc: 'Keeps rear 3D LED signature tail lamps active simultaneously with front DRL strips.',
        make: 'Renault',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '3040',
        byteIndex: 4,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_cornering_fog_lamps',
        nameKey: 'features.items.renault_cornering_fog_lamps.name',
        descKey: 'features.items.renault_cornering_fog_lamps.desc',
        defaultName: 'Static Cornering Fog Light Illumination',
        defaultDesc: 'Lights up the relevant front fog light during turning maneuvers below 40 km/h.',
        make: 'Renault',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '3050',
        byteIndex: 3,
        bitIndex: 5,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_seatbelt_buzzer_mute',
        nameKey: 'features.items.renault_seatbelt_buzzer_mute.name',
        descKey: 'features.items.renault_seatbelt_buzzer_mute.desc',
        defaultName: 'Seatbelt Warning Buzzer Sound Mute',
        defaultDesc: 'Mutes acoustic beeping for unfastened seatbelts (visual cluster alert remains active).',
        make: 'Renault',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '17',
        didHex: '3060',
        byteIndex: 0,
        bitIndex: 7,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_cornering_fog_lights',
        nameKey: 'features.items.renault_cornering_fog_lights.name',
        descKey: 'features.items.renault_cornering_fog_lights.desc',
        defaultName: 'Cornering Fog Lights Activation',
        defaultDesc: 'Automatically activates corresponding front fog light when steering wheel is turned or turn indicator is active.',
        make: 'Renault',
        category: 'LIGHTING',
        targetEcuHeader: '752',
        didHex: '0140',
        byteIndex: 1,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_overspeed_buzzer_disable',
        nameKey: 'features.items.renault_overspeed_buzzer_disable.name',
        descKey: 'features.items.renault_overspeed_buzzer_disable.desc',
        defaultName: '120 km/h Overspeed Acoustic Buzzer Mute',
        defaultDesc: 'Disables the continuous audible speed chime that triggers when driving over 120 km/h in Middle East spec vehicles.',
        make: 'Renault',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '743',
        didHex: '0210',
        byteIndex: 0,
        bitIndex: 5,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_clock_temp_cluster_display',
        nameKey: 'features.items.renault_clock_temp_cluster_display.name',
        descKey: 'features.items.renault_clock_temp_cluster_display.desc',
        defaultName: 'Instrument Cluster Clock & Ambient Temperature',
        defaultDesc: 'Enables external temperature and digital clock readout directly on center instrument cluster screen.',
        make: 'Renault',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '743',
        didHex: '0215',
        byteIndex: 2,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_camera_dynamic_guidelines',
        nameKey: 'features.items.renault_camera_dynamic_guidelines.name',
        descKey: 'features.items.renault_camera_dynamic_guidelines.desc',
        defaultName: 'Reverse Camera Dynamic Trajectory Guidelines',
        defaultDesc: 'Overlays steering-angle responsive dynamic curved trajectory guide lines on R-Link 2 rear camera screen.',
        make: 'Renault',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '744',
        didHex: '0305',
        byteIndex: 0,
        bitIndex: 4,
        requiresSecurityAccess: false,
        requiresExtendedSession: false,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_gear_shift_indicator_calib',
        nameKey: 'features.items.renault_gear_shift_indicator_calib.name',
        descKey: 'features.items.renault_gear_shift_indicator_calib.desc',
        defaultName: 'Gear Shift Indicator (GSI) Activation',
        defaultDesc: 'Enables dashboard upshift and downshift arrows for optimized fuel consumption and engine efficiency.',
        make: 'Renault',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '743',
        didHex: '0220',
        byteIndex: 1,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_coolant_temp_bar_unlock',
        nameKey: 'features.items.renault_coolant_temp_bar_unlock.name',
        descKey: 'features.items.renault_coolant_temp_bar_unlock.desc',
        defaultName: 'Engine Coolant Temperature Bar Gauge Unlock',
        defaultDesc: 'Unlocks digital engine coolant temperature bar graph on instrument clusters where it was factory hidden.',
        make: 'Renault',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '743',
        didHex: '0230',
        byteIndex: 3,
        bitIndex: 6,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_walkaway_lock_acoustic',
        nameKey: 'features.items.renault_walkaway_lock_acoustic.name',
        descKey: 'features.items.renault_walkaway_lock_acoustic.desc',
        defaultName: 'Hands-Free Card Walk-Away Acoustic Horn Beep',
        defaultDesc: 'Provides audible single horn confirmation when walking away from vehicle with Hands-Free key card.',
        make: 'Renault',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '752',
        didHex: '0145',
        byteIndex: 4,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'renault_rlink_video_in_motion',
        nameKey: 'features.items.renault_rlink_video_in_motion.name',
        descKey: 'features.items.renault_rlink_video_in_motion.desc',
        defaultName: 'R-Link 2 Video in Motion (VIM)',
        defaultDesc: 'Bypasses vehicle motion speed lock restriction for video playback on R-Link 2 multimedia touchscreen.',
        make: 'Renault',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '744',
        didHex: '0310',
        byteIndex: 2,
        bitIndex: 7,
        requiresSecurityAccess: false,
        requiresExtendedSession: false,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    }
];

