/**
 * StellantisProfile.ts — Stellantis, Fiat, Peugeot, Citroen, Opel, Alfa Romeo & Jeep OEM Coding
 */

import { OEMFeatureDefinition } from '../types';

export const STELLANTIS_OEM_FEATURES: OEMFeatureDefinition[] = [
    {
        id: 'stell_auto_mirror_fold_lock',
        nameKey: 'features.items.stell_auto_mirror_fold_lock.name',
        descKey: 'features.items.stell_auto_mirror_fold_lock.desc',
        defaultName: 'Automatic Mirror Folding on Key Lock',
        defaultDesc: 'Folds side mirrors automatically upon pressing lock button on key fob.',
        make: 'Fiat',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '09',
        didHex: '1010',
        byteIndex: 2,
        bitIndex: 3,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'stell_cornering_fog_lights',
        nameKey: 'features.items.stell_cornering_fog_lights.name',
        descKey: 'features.items.stell_cornering_fog_lights.desc',
        defaultName: 'Cornering Fog Light Illumination',
        defaultDesc: 'Activates corresponding front fog lamp when turn signal is on or steering angle > 30° below 40 km/h.',
        make: 'Peugeot',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '1020',
        byteIndex: 5,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'stell_needle_sweep_cluster',
        nameKey: 'features.items.stell_needle_sweep_cluster.name',
        descKey: 'features.items.stell_needle_sweep_cluster.desc',
        defaultName: 'Instrument Needle Sweep',
        defaultDesc: 'Performs gauge sweep on startup for analog/hybrid instrument clusters.',
        make: 'Alfa Romeo',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '17',
        didHex: '1030',
        byteIndex: 1,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'stell_acoustic_lock_chirp',
        nameKey: 'features.items.stell_acoustic_lock_chirp.name',
        descKey: 'features.items.stell_acoustic_lock_chirp.desc',
        defaultName: 'Acoustic Horn Chirp on Remote Lock',
        defaultDesc: 'Gives a short horn tap confirmation when vehicle doors successfully lock.',
        make: 'Jeep',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '09',
        didHex: '1040',
        byteIndex: 3,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'stell_rear_scandinavian_drl',
        nameKey: 'features.items.stell_rear_scandinavian_drl.name',
        descKey: 'features.items.stell_rear_scandinavian_drl.desc',
        defaultName: 'Rear Scandinavian DRL Tail Lights',
        defaultDesc: 'Illuminates rear tail lamps in conjunction with daytime running lights in Auto/0 mode.',
        make: 'Citroen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '1050',
        byteIndex: 4,
        bitIndex: 4,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'stell_lane_assist_memory_default',
        nameKey: 'features.items.stell_lane_assist_memory_default.name',
        descKey: 'features.items.stell_lane_assist_memory_default.desc',
        defaultName: 'Lane Keeping Assist Last State Memory',
        defaultDesc: 'Remembers the last ON/OFF state of Lane Keeping Assist instead of re-activating at every start.',
        make: 'Opel',
        category: 'ADAS_CALIBRATION',
        targetEcuHeader: 'A5',
        didHex: '1060',
        byteIndex: 1,
        bitIndex: 5,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'stell_sport_steering_weight_calibration',
        nameKey: 'features.items.stell_sport_steering_weight_calibration.name',
        descKey: 'features.items.stell_sport_steering_weight_calibration.desc',
        defaultName: 'Dynamic Electric Power Steering (EPS) Weight Curve',
        defaultDesc: 'Increases steering wheel resistance and centering feel for a firmer, sportier feedback.',
        make: 'Alfa Romeo',
        category: 'PERFORMANCE',
        targetEcuHeader: '44',
        didHex: '1070',
        byteIndex: 0,
        bitIndex: 3,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'stell_digital_speedo_unit_toggle',
        nameKey: 'features.items.stell_digital_speedo_unit_toggle.name',
        descKey: 'features.items.stell_digital_speedo_unit_toggle.desc',
        defaultName: 'Digital Speedometer km/h & mph Dual Display',
        defaultDesc: 'Shows numeric speed readout in both km/h and mph simultaneously in the center LCD.',
        make: 'Fiat',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '17',
        didHex: '1080',
        byteIndex: 2,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    }
];
