/**
 * VagProfile.ts — Volkswagen, Audi, SEAT, Skoda & Cupra OEM Feature Profile
 * Supports MQB, MQB-Evo, PQ35, MLB-Evo platforms (BCM 09, Cluster 17, Infotainment 5F, etc.)
 */

import { OEMFeatureDefinition } from '../types';

export const VAG_OEM_FEATURES: OEMFeatureDefinition[] = [
    {
        id: 'vag_oil_service_reset',
        nameKey: 'features.items.vag_oil_service_reset.name',
        descKey: 'features.items.vag_oil_service_reset.desc',
        defaultName: 'Oil Service Interval Reset (VAG)',
        defaultDesc: 'Resets oil change service counter and inspection interval for VAG vehicles.',
        make: 'Volkswagen',
        category: 'SERVICE_MAINTENANCE',
        targetEcuHeader: '17',
        didHex: '0200',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_staging_needle_sweep',
        nameKey: 'features.items.vag_staging_needle_sweep.name',
        descKey: 'features.items.vag_staging_needle_sweep.desc',
        defaultName: 'Gauge Staging / Needle Sweep',
        defaultDesc: 'Sweeps instrument needles to maximum upon ignition start.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '17',
        didHex: '0D04',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_acoustic_lock_confirmation',
        nameKey: 'features.items.vag_acoustic_lock_confirmation.name',
        descKey: 'features.items.vag_acoustic_lock_confirmation.desc',
        defaultName: 'Acoustic Lock Confirmation Chirp',
        defaultDesc: 'Emits a short horn confirmation chirp upon key fob locking.',
        make: 'Volkswagen',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '09',
        didHex: '0620',
        byteIndex: 1,
        bitIndex: 3,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_drl_brightness_multi',
        nameKey: 'features.items.vag_drl_brightness_multi.name',
        descKey: 'features.items.vag_drl_brightness_multi.desc',
        defaultName: 'Daytime Running Lights (DRL) Brightness Adjustment',
        defaultDesc: 'Adjust LED DRL intensity level for low-beam / parking mode.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0A12',
        byteIndex: 2,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.drl25', defaultLabel: '25% Dimmed', valueHex: '19' },
            { labelKey: 'features.options.drl50', defaultLabel: '50% Medium', valueHex: '32' },
            { labelKey: 'features.options.drl75', defaultLabel: '75% Bright', valueHex: '4B' },
            { labelKey: 'features.options.drl100', defaultLabel: '100% Full Power', valueHex: '64' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_mirror_dip_reverse',
        nameKey: 'features.items.vag_mirror_dip_reverse.name',
        descKey: 'features.items.vag_mirror_dip_reverse.desc',
        defaultName: 'Passenger Mirror Dip on Reverse Gear',
        defaultDesc: 'Tilts passenger side mirror downward when shifting into reverse to assist curb parking.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '52',
        didHex: '0B30',
        byteIndex: 4,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_lap_timer_oil_temp',
        nameKey: 'features.items.vag_lap_timer_oil_temp.name',
        descKey: 'features.items.vag_lap_timer_oil_temp.desc',
        defaultName: 'Lap Timer & Oil Temperature in Gauge Cluster',
        defaultDesc: 'Unlocks racetrack lap timer stopwatch and real-time engine oil temperature readout.',
        make: 'Audi',
        category: 'PERFORMANCE',
        targetEcuHeader: '17',
        didHex: '0C40',
        byteIndex: 1,
        bitIndex: 3,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_rear_scandinavian_drl',
        nameKey: 'features.items.vag_rear_scandinavian_drl.name',
        descKey: 'features.items.vag_rear_scandinavian_drl.desc',
        defaultName: 'Scandinavian DRL (Rear Tail Lights ON with DRL)',
        defaultDesc: 'Illuminates rear LED tail lights constantly when front daytime running lights are active.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0D50',
        byteIndex: 5,
        bitIndex: 6,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_drl_handbrake_off',
        nameKey: 'features.items.vag_drl_handbrake_off.name',
        descKey: 'features.items.vag_drl_handbrake_off.desc',
        defaultName: 'Turn OFF DRL when Handbrake is Engaged',
        defaultDesc: 'Automatically turns off daytime running lights whenever parking brake is pulled up.',
        make: 'Seat',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0E60',
        byteIndex: 3,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_drl_menu_in_mib',
        nameKey: 'features.items.vag_drl_menu_in_mib.name',
        descKey: 'features.items.vag_drl_menu_in_mib.desc',
        defaultName: 'DRL ON/OFF Toggle Switch in Touchscreen Menu',
        defaultDesc: 'Adds Daytime Running Lights toggle checkbox under Vehicle Lights settings in MIB screen.',
        make: 'Skoda',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0F70',
        byteIndex: 2,
        bitIndex: 7,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_rain_closing_windows',
        nameKey: 'features.items.vag_rain_closing_windows.name',
        descKey: 'features.items.vag_rain_closing_windows.desc',
        defaultName: 'Rain Closing (Automatic Windows & Sunroof Close)',
        defaultDesc: 'Closes all open windows and panoramic sunroof if parked vehicle detects rain on windshield.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '09',
        didHex: '1080',
        byteIndex: 0,
        bitIndex: 5,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_audi_dynamic_throttle',
        nameKey: 'features.items.vag_audi_dynamic_throttle.name',
        descKey: 'features.items.vag_audi_dynamic_throttle.desc',
        defaultName: 'Audi Linear Direct Throttle Response',
        defaultDesc: 'Removes electronic pedal lag by switching from time-gradient to direct linear throttle mapping.',
        make: 'Audi',
        category: 'PERFORMANCE',
        targetEcuHeader: '01',
        didHex: '1190',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'vag_xds_differential_sensitivity',
        nameKey: 'features.items.vag_xds_differential_sensitivity.name',
        descKey: 'features.items.vag_xds_differential_sensitivity.desc',
        defaultName: 'XDS Electronic Differential Lock Sensitivity',
        defaultDesc: 'Increases cornering traction and reduces understeer by applying higher inner-wheel brake torque.',
        make: 'Cupra',
        category: 'PERFORMANCE',
        targetEcuHeader: '03',
        didHex: '12A0',
        byteIndex: 2,
        bitIndex: 4,
        options: [
            { labelKey: 'features.options.xdsStandard', defaultLabel: 'Standard (Medium)', valueHex: '00' },
            { labelKey: 'features.options.xdsStrong', defaultLabel: 'Strong (GTI / R)', valueHex: '02' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'vag_offroad_display_mib',
        nameKey: 'features.items.vag_offroad_display_mib.name',
        descKey: 'features.items.vag_offroad_display_mib.desc',
        defaultName: 'Off-Road Display & Compass in Infotainment',
        defaultDesc: 'Unlocks Off-Road telemetry screen displaying steering angle, compass, and oil/coolant temperatures.',
        make: 'Skoda',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '5F',
        didHex: '13B0',
        byteIndex: 1,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_highbeam_assist_memory',
        nameKey: 'features.items.vag_highbeam_assist_memory.name',
        descKey: 'features.items.vag_highbeam_assist_memory.desc',
        defaultName: 'High-Beam Assist (Light Assist) State Memory',
        defaultDesc: 'Maintains Auto High-Beam Assist active across ignition cycles so driver does not have to re-arm it.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '14C0',
        byteIndex: 4,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_comfort_turn_signals_count',
        nameKey: 'features.items.vag_comfort_turn_signals_count.name',
        descKey: 'features.items.vag_comfort_turn_signals_count.desc',
        defaultName: 'Comfort Turn Signal Flash Cycles',
        defaultDesc: 'Changes number of highway lane-change blinker pulses from standard 3 to 4 or 5.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '15D0',
        byteIndex: 0,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.blink3', defaultLabel: '3 Flashes (Default)', valueHex: '03' },
            { labelKey: 'features.options.blink4', defaultLabel: '4 Flashes', valueHex: '04' },
            { labelKey: 'features.options.blink5', defaultLabel: '5 Flashes', valueHex: '05' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    }
];
