/**
 * VagProfile.ts — Volkswagen, Audi, SEAT, Skoda & Cupra OEM Feature Profile
 * Supports MQB, MQB-Evo, PQ35, MLB-Evo platforms (BCM 09, Cluster 17, Infotainment 5F, etc.)
 */

import { OEMFeatureDefinition } from '../types';

export const VAG_OEM_FEATURES: OEMFeatureDefinition[] = [
    {
        id: 'vag_oil_service_reset',
        nameKey: 'features.items.vag_oil_service_reset.name',
        descKey: 'features.items.vag_oil_service_reset.desc',
        defaultName: 'Oil Service Interval Reset',
        defaultDesc: 'Resets oil change service counter and inspection interval for VAG vehicles.',
        make: 'Volkswagen',
        category: 'SERVICE_MAINTENANCE',
        targetEcuHeader: '17',
        didHex: '0200',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_staging_needle_sweep',
        nameKey: 'features.items.vag_staging_needle_sweep.name',
        descKey: 'features.items.vag_staging_needle_sweep.desc',
        defaultName: 'Gauge Staging / Needle Sweep',
        defaultDesc: 'Sweeps instrument needles to maximum upon ignition start.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '17',
        didHex: '0D04',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_acoustic_lock_confirmation',
        nameKey: 'features.items.vag_acoustic_lock_confirmation.name',
        descKey: 'features.items.vag_acoustic_lock_confirmation.desc',
        defaultName: 'Acoustic Lock Confirmation Chirp',
        defaultDesc: 'Emits a short horn confirmation chirp upon key fob locking.',
        make: 'Volkswagen',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '09',
        didHex: '0620',
        byteIndex: 1,
        bitIndex: 3,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_drl_brightness_multi',
        nameKey: 'features.items.vag_drl_brightness_multi.name',
        descKey: 'features.items.vag_drl_brightness_multi.desc',
        defaultName: 'Daytime Running Lights Brightness Adjustment',
        defaultDesc: 'Adjust LED DRL intensity level for low-beam / parking mode.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0A12',
        byteIndex: 2,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.drl25', defaultLabel: '25% Dimmed', valueHex: '19' },
            { labelKey: 'features.options.drl50', defaultLabel: '50% Medium', valueHex: '32' },
            { labelKey: 'features.options.drl75', defaultLabel: '75% Bright', valueHex: '4B' },
            { labelKey: 'features.options.drl100', defaultLabel: '100% Full Power', valueHex: '64' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_mirror_dip_reverse',
        nameKey: 'features.items.vag_mirror_dip_reverse.name',
        descKey: 'features.items.vag_mirror_dip_reverse.desc',
        defaultName: 'Passenger Mirror Dip on Reverse Gear',
        defaultDesc: 'Tilts passenger side mirror downward when shifting into reverse to assist curb parking.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '52',
        didHex: '0B30',
        byteIndex: 4,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_lap_timer_oil_temp',
        nameKey: 'features.items.vag_lap_timer_oil_temp.name',
        descKey: 'features.items.vag_lap_timer_oil_temp.desc',
        defaultName: 'Lap Timer & Oil Temperature in Gauge Cluster',
        defaultDesc: 'Unlocks racetrack lap timer stopwatch and real-time engine oil temperature readout.',
        make: 'Audi',
        category: 'PERFORMANCE',
        targetEcuHeader: '17',
        didHex: '0C40',
        byteIndex: 1,
        bitIndex: 3,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_rear_scandinavian_drl',
        nameKey: 'features.items.vag_rear_scandinavian_drl.name',
        descKey: 'features.items.vag_rear_scandinavian_drl.desc',
        defaultName: 'Scandinavian DRL',
        defaultDesc: 'Illuminates rear LED tail lights constantly when front daytime running lights are active.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0D50',
        byteIndex: 5,
        bitIndex: 6,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_drl_handbrake_off',
        nameKey: 'features.items.vag_drl_handbrake_off.name',
        descKey: 'features.items.vag_drl_handbrake_off.desc',
        defaultName: 'Turn OFF DRL when Handbrake is Engaged',
        defaultDesc: 'Automatically turns off daytime running lights whenever parking brake is pulled up.',
        make: 'Seat',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0E60',
        byteIndex: 3,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_drl_menu_in_mib',
        nameKey: 'features.items.vag_drl_menu_in_mib.name',
        descKey: 'features.items.vag_drl_menu_in_mib.desc',
        defaultName: 'DRL ON/OFF Toggle Switch in Touchscreen Menu',
        defaultDesc: 'Adds Daytime Running Lights toggle checkbox under Vehicle Lights settings in MIB screen.',
        make: 'Skoda',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0F70',
        byteIndex: 2,
        bitIndex: 7,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_rain_closing_windows',
        nameKey: 'features.items.vag_rain_closing_windows.name',
        descKey: 'features.items.vag_rain_closing_windows.desc',
        defaultName: 'Rain Closing',
        defaultDesc: 'Closes all open windows and panoramic sunroof if parked vehicle detects rain on windshield.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '09',
        didHex: '1080',
        byteIndex: 0,
        bitIndex: 5,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_audi_dynamic_throttle',
        nameKey: 'features.items.vag_audi_dynamic_throttle.name',
        descKey: 'features.items.vag_audi_dynamic_throttle.desc',
        defaultName: 'Audi Linear Direct Throttle Response',
        defaultDesc: 'Removes electronic pedal lag by switching from time-gradient to direct linear throttle mapping.',
        make: 'Audi',
        category: 'PERFORMANCE',
        targetEcuHeader: '01',
        didHex: '1190',
        byteIndex: 0,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'vag_xds_differential_sensitivity',
        nameKey: 'features.items.vag_xds_differential_sensitivity.name',
        descKey: 'features.items.vag_xds_differential_sensitivity.desc',
        defaultName: 'XDS Electronic Differential Lock Sensitivity',
        defaultDesc: 'Increases cornering traction and reduces understeer by applying higher inner-wheel brake torque.',
        make: 'Cupra',
        category: 'PERFORMANCE',
        targetEcuHeader: '03',
        didHex: '12A0',
        byteIndex: 2,
        bitIndex: 4,
        options: [
            { labelKey: 'features.options.xdsStandard', defaultLabel: 'Standard (Medium)', valueHex: '00' },
            { labelKey: 'features.options.xdsStrong', defaultLabel: 'Strong (GTI / R)', valueHex: '02' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'vag_offroad_display_mib',
        nameKey: 'features.items.vag_offroad_display_mib.name',
        descKey: 'features.items.vag_offroad_display_mib.desc',
        defaultName: 'Off-Road Display & Compass in Infotainment',
        defaultDesc: 'Unlocks Off-Road telemetry screen displaying steering angle, compass, and oil/coolant temperatures.',
        make: 'Skoda',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '5F',
        didHex: '13B0',
        byteIndex: 1,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_highbeam_assist_memory',
        nameKey: 'features.items.vag_highbeam_assist_memory.name',
        descKey: 'features.items.vag_highbeam_assist_memory.desc',
        defaultName: 'High-Beam Assist (Light Assist) State Memory',
        defaultDesc: 'Maintains Auto High-Beam Assist active across ignition cycles so driver does not have to re-arm it.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '14C0',
        byteIndex: 4,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_comfort_turn_signals_count',
        nameKey: 'features.items.vag_comfort_turn_signals_count.name',
        descKey: 'features.items.vag_comfort_turn_signals_count.desc',
        defaultName: 'Comfort Turn Signal Flash Cycles',
        defaultDesc: 'Changes number of highway lane-change blinker pulses from standard 3 to 4 or 5.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '15D0',
        byteIndex: 0,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.blink3', defaultLabel: '3 Flashes (Default)', valueHex: '03' },
            { labelKey: 'features.options.blink4', defaultLabel: '4 Flashes', valueHex: '04' },
            { labelKey: 'features.options.blink5', defaultLabel: '5 Flashes', valueHex: '05' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_brake_disc_drying_abs',
        nameKey: 'features.items.vag_brake_disc_drying_abs.name',
        descKey: 'features.items.vag_brake_disc_drying_abs.desc',
        defaultName: 'Brake Disc Drying (BDD)',
        defaultDesc: 'Periodically applies light brake pad pressure in wet conditions to remove water film and improve wet stopping distance.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '03',
        didHex: '0901',
        byteIndex: 0,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.bddOff', defaultLabel: 'Disabled', valueHex: '00' },
            { labelKey: 'features.options.bddWeak', defaultLabel: 'Weak', valueHex: '01' },
            { labelKey: 'features.options.bddMed', defaultLabel: 'Medium (Standard)', valueHex: '02' },
            { labelKey: 'features.options.bddStrong', defaultLabel: 'Strong', valueHex: '03' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_hill_hold_assist_response',
        nameKey: 'features.items.vag_hill_hold_assist_response.name',
        descKey: 'features.items.vag_hill_hold_assist_response.desc',
        defaultName: 'Hill Hold Assist (HHC) Release Timing',
        defaultDesc: 'Adjusts release timing threshold of Hill Hold Control when accelerating from an incline.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '03',
        didHex: '0915',
        byteIndex: 0,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.hhcEarly', defaultLabel: 'Early Release', valueHex: '00' },
            { labelKey: 'features.options.hhcNormal', defaultLabel: 'Normal Release', valueHex: '01' },
            { labelKey: 'features.options.hhcLate', defaultLabel: 'Late Release', valueHex: '02' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_seat_heating_memory',
        nameKey: 'features.items.vag_seat_heating_memory.name',
        descKey: 'features.items.vag_seat_heating_memory.desc',
        defaultName: 'Seat Heating Level Memory',
        defaultDesc: 'Retains driver and front passenger seat heater level setting across ignition off and on cycles.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '08',
        didHex: '1102',
        byteIndex: 1,
        bitIndex: 2,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_soundaktor_volume',
        nameKey: 'features.items.vag_soundaktor_volume.name',
        descKey: 'features.items.vag_soundaktor_volume.desc',
        defaultName: 'Soundaktor Interior Engine Sound Volume',
        defaultDesc: 'Adjusts volume percentage of synthetic engine cabin acoustic actuator from completely silent to full throttle.',
        make: 'Volkswagen',
        category: 'SOUND_ALERTS',
        targetEcuHeader: 'A9',
        didHex: '3E01',
        byteIndex: 0,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.sound0', defaultLabel: '0% (Completely Off)', valueHex: '00' },
            { labelKey: 'features.options.sound50', defaultLabel: '50% (Subtle)', valueHex: '32' },
            { labelKey: 'features.options.sound100', defaultLabel: '100% (Factory Max)', valueHex: '64' }
        ],
        requiresSecurityAccess: false,
        requiresExtendedSession: false,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_rear_tear_wiping',
        nameKey: 'features.items.vag_rear_tear_wiping.name',
        descKey: 'features.items.vag_rear_tear_wiping.desc',
        defaultName: 'Rear Wiper Tear Drop Wiping',
        defaultDesc: 'Executes one final wipe 5 seconds after rear washer spray to clear residual dripping water.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '09',
        didHex: '0214',
        byteIndex: 2,
        bitIndex: 4,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_pace_car_blinkers',
        nameKey: 'features.items.vag_pace_car_blinkers.name',
        descKey: 'features.items.vag_pace_car_blinkers.desc',
        defaultName: 'Pace-Car Alternating Turn Signals',
        defaultDesc: 'Alternates inner and outer rear indicator lighting in counter-phase during hazard flashers.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '052A',
        byteIndex: 3,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_cornering_lights_speed_threshold',
        nameKey: 'features.items.vag_cornering_lights_speed_threshold.name',
        descKey: 'features.items.vag_cornering_lights_speed_threshold.desc',
        defaultName: 'Cornering Fog Light Speed Threshold',
        defaultDesc: 'Increases maximum speed threshold for fog light cornering assist illumination from 40 to 60 km/h.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0540',
        byteIndex: 0,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.speed40', defaultLabel: '40 km/h (Factory)', valueHex: '28' },
            { labelKey: 'features.options.speed50', defaultLabel: '50 km/h', valueHex: '32' },
            { labelKey: 'features.options.speed60', defaultLabel: '60 km/h (Extended)', valueHex: '3C' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_reverse_rear_wiper_disable',
        nameKey: 'features.items.vag_reverse_rear_wiper_disable.name',
        descKey: 'features.items.vag_reverse_rear_wiper_disable.desc',
        defaultName: 'Reverse Gear Automatic Rear Wipe Disable',
        defaultDesc: 'Prevents rear wiper from automatically wiping a dry or iced window when engaging reverse gear.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '09',
        didHex: '0220',
        byteIndex: 1,
        bitIndex: 3,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_coming_home_fog_lights',
        nameKey: 'features.items.vag_coming_home_fog_lights.name',
        descKey: 'features.items.vag_coming_home_fog_lights.desc',
        defaultName: 'Coming Home via Fog Lights',
        defaultDesc: 'Illuminates front fog lights instead of low beam headlights for Coming Home welcome exterior lighting.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0518',
        byteIndex: 0,
        bitIndex: 2,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_refuel_gallons_display',
        nameKey: 'features.items.vag_refuel_gallons_display.name',
        descKey: 'features.items.vag_refuel_gallons_display.desc',
        defaultName: 'Volume to be Replenished (Refuel Liters)',
        defaultDesc: 'Displays exact liters of fuel required to top off fuel tank on instrument cluster MFD screen.',
        make: 'Volkswagen',
        category: 'DISPLAY_INSTRUMENT',
        targetEcuHeader: '17',
        didHex: '2210',
        byteIndex: 1,
        bitIndex: 0,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_seatbelt_warning_chime',
        nameKey: 'features.items.vag_seatbelt_warning_chime.name',
        descKey: 'features.items.vag_seatbelt_warning_chime.desc',
        defaultName: 'Seatbelt Acoustic Warning Chime',
        defaultDesc: 'Mutes persistent audible seatbelt chime while preserving instrument cluster visual warning icon.',
        make: 'Volkswagen',
        category: 'SOUND_ALERTS',
        targetEcuHeader: '17',
        didHex: '0308',
        byteIndex: 0,
        bitIndex: 1,
        requiresSecurityAccess: false,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'MEDIUM'
    },
    {
        id: 'vag_sunroof_comfort_mode',
        nameKey: 'features.items.vag_sunroof_comfort_mode.name',
        descKey: 'features.items.vag_sunroof_comfort_mode.desc',
        defaultName: 'Panoramic Sunroof Comfort Opening Mode',
        defaultDesc: 'Configures remote key fob long-press action to either tilt or fully slide open panoramic sunroof.',
        make: 'Volkswagen',
        category: 'DRIVING_COMFORT',
        targetEcuHeader: '09',
        didHex: '0612',
        byteIndex: 2,
        bitIndex: 1,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_1_CODING',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_scandinavian_rear_drl',
        nameKey: 'features.items.vag_scandinavian_rear_drl.name',
        descKey: 'features.items.vag_scandinavian_rear_drl.desc',
        defaultName: 'Scandinavian Daytime Running Tail Lights',
        defaultDesc: 'Keeps rear tail lights active alongside daytime running lights for enhanced rear visibility in tunnels.',
        make: 'Volkswagen',
        category: 'LIGHTING',
        targetEcuHeader: '09',
        didHex: '0535',
        byteIndex: 4,
        bitIndex: 0,
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'LOW'
    },
    {
        id: 'vag_xds_differential_strength',
        nameKey: 'features.items.vag_xds_differential_strength.name',
        descKey: 'features.items.vag_xds_differential_strength.desc',
        defaultName: 'XDS Electronic Differential Lock Strength',
        defaultDesc: 'Adjusts brake-based torque vectoring aggressiveness on inner drive wheels to reduce understeer in sharp corners.',
        make: 'Volkswagen',
        category: 'PERFORMANCE',
        targetEcuHeader: '03',
        didHex: '0920',
        byteIndex: 0,
        bitIndex: 0,
        bitWidth: 8,
        options: [
            { labelKey: 'features.options.xdsStandard', defaultLabel: 'Standard (Factory)', valueHex: '00' },
            { labelKey: 'features.options.xdsMedium', defaultLabel: 'Medium', valueHex: '01' },
            { labelKey: 'features.options.xdsStrong', defaultLabel: 'Strong (Sport Track)', valueHex: '02' }
        ],
        requiresSecurityAccess: true,
        securityLevel: 1,
        requiresExtendedSession: true,
        safetyLevel: 'LEVEL_2_ADAPTATION',
        riskLevel: 'MEDIUM'
    }
];

