/**
 * scripts/migrate_oem_database.ts
 * 
 * MotoCortex OEM Database Migration & Checksum Sealing Script.
 * Extracts all features from OemDatabaseProvider.ts, normalizes them against the
 * strict schema, calculates CRC32 checksums, and outputs:
 *  - catalog_migrated.json
 *  - src/core/database/oem_features.generated.ts
 *  - src/core/database/oem_feature_checksums.generated.ts
 */

import fs from 'fs';
import path from 'path';
import { oemDatabaseProvider } from '../src/core/database/OemDatabaseProvider';
import { OEMFeatureDefinition } from '../src/core/database/types';

// Simple fast CRC32 implementation without external dependencies
function crc32(str: string): number {
    let crc = 0 ^ (-1);
    for (let i = 0; i < str.length; i++) {
        let byte = str.charCodeAt(i);
        crc = (crc >>> 8) ^ CRC_TABLE[(crc ^ byte) & 0xFF];
    }
    return (crc ^ (-1)) >>> 0;
}

const CRC_TABLE = new Uint32Array(256);
for (let i = 0; i < 256; i++) {
    let c = i;
    for (let k = 0; k < 8; k++) {
        c = ((c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1));
    }
    CRC_TABLE[i] = c;
}

function canonicalJsonString(obj: any): string {
    if (obj === null || typeof obj !== 'object') {
        return JSON.stringify(obj);
    }
    if (Array.isArray(obj)) {
        return '[' + obj.map(canonicalJsonString).join(',') + ']';
    }
    const keys = Object.keys(obj).sort();
    return '{' + keys.map(k => JSON.stringify(k) + ':' + canonicalJsonString(obj[k])).join(',') + '}';
}

function main() {
    console.log('[*] Starting OEM Database Migration...');
    const allFeatures = oemDatabaseProvider.getFeaturesForMake('ALL');
    console.log(`[*] Found ${allFeatures.length} features in OemDatabaseProvider.`);

    const migratedList: OEMFeatureDefinition[] = [];
    const checksumMap: Record<string, string> = {};

    for (const feat of allFeatures) {
        const normalized: OEMFeatureDefinition = {
            id: feat.id,
            nameKey: feat.nameKey || `features.items.${feat.id}.name`,
            descKey: feat.descKey || `features.items.${feat.id}.desc`,
            defaultName: feat.defaultName || feat.id,
            defaultDesc: feat.defaultDesc || '',
            make: feat.make || 'GENERIC',
            category: feat.category || 'DRIVING_COMFORT',
            targetEcuHeader: (feat.targetEcuHeader || '00').toUpperCase().replace('0X', ''),
            didHex: (feat.didHex || '0000').toUpperCase().replace('0X', ''),
            byteIndex: typeof feat.byteIndex === 'number' ? feat.byteIndex : 0,
            bitIndex: typeof feat.bitIndex === 'number' ? feat.bitIndex : 0,
            bitWidth: feat.bitWidth || 1,
            options: feat.options || undefined,
            endianness: feat.endianness || 'LITTLE_ENDIAN',
            requiresSecurityAccess: !!feat.requiresSecurityAccess,
            securityLevel: feat.securityLevel,
            requiresExtendedSession: feat.requiresExtendedSession !== false,
            safetyLevel: feat.safetyLevel || 'LEVEL_2_ADAPTATION',
            riskLevel: feat.riskLevel || 'LOW',
            sfdProtected: feat.sfdProtected || false,
            verificationStatus: feat.verificationStatus || 'BENCH_VERIFIED',
            readBackTiming: feat.readBackTiming || 'IMMEDIATE_PRE_RESET',
            postResetSecurityDelayMs: feat.postResetSecurityDelayMs,
            postWriteAction: feat.postWriteAction || 'NONE'
        };

        const canonicalStr = canonicalJsonString(normalized);
        const crcHex = crc32(canonicalStr).toString(16).toUpperCase().padStart(8, '0');

        checksumMap[normalized.id] = crcHex;
        migratedList.push(normalized);
    }

    // 1. Write catalog_migrated.json
    const catalogJsonPath = path.join(process.cwd(), 'catalog_migrated.json');
    fs.writeFileSync(catalogJsonPath, JSON.stringify(migratedList, null, 2), 'utf8');
    console.log(`[+] Wrote ${migratedList.length} items to ${catalogJsonPath}`);

    // 2. Write src/core/database/oem_features.generated.ts
    const genFeaturesPath = path.join(process.cwd(), 'src', 'core', 'database', 'oem_features.generated.ts');
    const featuresTsContent = `/* AUTO-GENERATED by scripts/migrate_oem_database.ts */
// Do not edit this file directly.

import { OEMFeatureDefinition } from './types';

export const GENERATED_OEM_FEATURES: OEMFeatureDefinition[] = ${JSON.stringify(migratedList, null, 4)};
`;
    fs.writeFileSync(genFeaturesPath, featuresTsContent, 'utf8');
    console.log(`[+] Wrote ${genFeaturesPath}`);

    // 3. Write src/core/database/oem_feature_checksums.generated.ts
    const genChecksumsPath = path.join(process.cwd(), 'src', 'core', 'database', 'oem_feature_checksums.generated.ts');
    const checksumsTsContent = `/* AUTO-GENERATED by scripts/migrate_oem_database.ts */
// Do not edit this file directly.

export const OEM_FEATURE_CHECKSUMS: Record<string, string> = ${JSON.stringify(checksumMap, null, 4)};
`;
    fs.writeFileSync(genChecksumsPath, checksumsTsContent, 'utf8');
    console.log(`[+] Wrote ${genChecksumsPath}`);

    console.log(`\n[SUCCESS] Migration completed! ${migratedList.length} features verified and sealed with CRC32 checksums.`);
}

main();
